# https://github.com/cloudfoundry/runtime-ci/blob/master/ci/infrastructure.yml

resources:

# Plan patches
# - name: bosh-bootloader
#   type: git
#   source:
#     branch: master
#     uri: https://github.com/cloudfoundry/bosh-bootloader

- name: relint-envs
  type: git
  source:
    branch: master
    uri: https://github.com/aegershman/deployments-state.git
    username: ((relint_envs_username))
    password: ((relint_envs_password))


# Code repos
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

jobs:

- name: bbl-up #setup-infrastructure-experimental
  plan:
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: relint-envs
  - task: setup-infrastructure
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_STATE_DIR: environments/test/hermione/bbl-state
      BBL_IAAS: aws
      BBL_AWS_REGION: us-east-2
      BBL_AWS_ACCESS_KEY_ID: ((bbl_aws_access_key_id))
      BBL_AWS_SECRET_ACCESS_KEY: ((bbl_aws_secret_access_key))
      BBL_LB_CERT: ((bbl_lbs_certificate))
      BBL_LB_KEY: ((bbl_lbs_private_key))
      BBL_LB_CERT_CHAIN: ((bbl_lbs_ca))
      LB_DOMAIN: cf.gershman.io #hermione.cf-app.com
      BBL_ENV_NAME: bbl-gershman #hermione-experimental
    input_mapping:
      bbl-state: relint-envs
      bbl-config: relint-envs
    ensure:
      put: relint-envs
      params:
        repository: updated-bbl-state
        rebase: true
