# https://github.com/kubernetes/ingress-nginx/blob/6048e63daa2bd074a843f3caf344b1816bd703bc/charts/ingress-nginx/values.yaml#L429
# https://github.com/kubernetes/minikube/pull/5519/files
---
controller:
  replicaCount: 1
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    type: NodePort
  config:
    proxy-body-size: 64m
    proxy-buffer-size: 16k
  metrics:
    enabled: true
    service:
      type: ClusterIP
    serviceMonitor:
      enabled: true
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  terminationGracePeriodSeconds: 10

defaultBackend:
  enabled: false
