# https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml
# https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/third-party-addons/opentracing.md
# https://github.com/kubernetes/ingress-nginx/pull/4983
# https://github.com/kubernetes/minikube/pull/5519/files
# https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
---
controller:
  replicaCount: 1
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    type: NodePort
  config:
    enable-opentracing: "true"
    jaeger-collector-host: jaeger-operator-jaeger-agent.jaeger-operator.svc.cluster.local
    proxy-body-size: 64m
    proxy-buffer-size: 16k
  metrics:
    enabled: true
    service:
      type: ClusterIP
    serviceMonitor:
      enabled: true
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  terminationGracePeriodSeconds: 10

defaultBackend:
  enabled: false
