postgresql:
  enabled: false

web:
  enabled: false

worker:
  replicas: 1

persistence:
  worker:
    size: 256M

concourse:
  worker:
    tsa:
      hosts:
      - concourse-web-web.concourse-web.svc.cluster.local:2222
