---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    quarks.cloudfoundry.org/monitored: cfo
    quarks.cloudfoundry.org/qjob-service-account: qjob-persist-output
  name: kubecf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cf-operator-quarks-job
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qjob-persist-output
  namespace: kubecf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cf-operator-quarks-secret
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cf-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cf-operator-quarks-job
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - quarks.cloudfoundry.org
  resources:
  - quarksjobs
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - quarks.cloudfoundry.org
  resources:
  - quarksjobs/status
  verbs:
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: qjob-persist-output
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - quarks.cloudfoundry.org
  resources:
  - quarksjobs
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cf-operator-quarks-secret
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - approve
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - kubernetes.io/legacy-unknown
  resources:
  - signers
  verbs:
  - approve
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - create
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - quarks.cloudfoundry.org
  resources:
  - quarkssecrets
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - quarks.cloudfoundry.org
  resources:
  - quarkssecrets/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cf-operator-cluster
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - approve
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - kubernetes.io/legacy-unknown
  resources:
  - signers
  verbs:
  - approve
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - delete
  - list
  - update
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - create
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
- apiGroups:
  - quarks.cloudfoundry.org
  resources:
  - quarksjobs
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - quarks.cloudfoundry.org
  resources:
  - boshdeployments
  - quarksstatefulsets
  - quarkssecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quarks.cloudfoundry.org
  resources:
  - boshdeployments/status
  - quarkssecrets/status
  - quarksstatefulsets/status
  verbs:
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cf-operator-quarks-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cf-operator-quarks-job
subjects:
- kind: ServiceAccount
  name: cf-operator-quarks-job
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cf-operator-quarks-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cf-operator-quarks-secret
subjects:
- kind: ServiceAccount
  name: cf-operator-quarks-secret
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: cf-operator-webhook
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qjob-persist-output
  namespace: kubecf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: qjob-persist-output
subjects:
- kind: ServiceAccount
  name: qjob-persist-output
---
apiVersion: v1
kind: Service
metadata:
  name: cf-operator-webhook
  namespace: default
spec:
  ports:
  - port: 443
    targetPort: 2999
  selector:
    name: cf-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: v1.0.206
          Type: resolved
          URL: cfcontainerization/quarks-job:v1.0.206
        URL: index.docker.io/cfcontainerization/quarks-job@sha256:d0e552cdc3fa9e8aac2b69d619a3a2cd2db82c6f1ca582ebc41f994e8913f4d9
  name: cf-operator-quarks-job
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: quarks-job
  template:
    metadata:
      labels:
        name: quarks-job
    spec:
      containers:
      - command:
        - quarks-job
        env:
        - name: APPLY_CRD
          value: "true"
        - name: LOG_LEVEL
          value: debug
        - name: MAX_WORKERS
          value: "1"
        - name: CTX_TIMEOUT
          value: "300"
        - name: MELTDOWN_DURATION
          value: "60"
        - name: MELTDOWN_REQUEUE_AFTER
          value: "30"
        - name: MONITORED_ID
          value: cfo
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: quarks-job
        - name: DOCKER_IMAGE_ORG
          value: cfcontainerization
        - name: DOCKER_IMAGE_REPOSITORY
          value: quarks-job
        - name: DOCKER_IMAGE_TAG
          value: v1.0.206
        - name: DOCKER_IMAGE_PULL_POLICY
          value: IfNotPresent
        image: index.docker.io/cfcontainerization/quarks-job@sha256:d0e552cdc3fa9e8aac2b69d619a3a2cd2db82c6f1ca582ebc41f994e8913f4d9
        imagePullPolicy: IfNotPresent
        name: quarks-job
        ports:
        - containerPort: 60000
          name: metrics
      serviceAccountName: cf-operator-quarks-job
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: v1.0.744
          Type: resolved
          URL: cfcontainerization/quarks-secret:v1.0.744
        URL: index.docker.io/cfcontainerization/quarks-secret@sha256:4a3fbb75f4d767ed9e7c194a12d91f17a3eb3eb1392c1045cd0871579fc70dc4
  name: cf-operator-quarks-secret
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: quarks-secret
  template:
    metadata:
      labels:
        name: quarks-secret
    spec:
      containers:
      - command:
        - quarks-secret
        env:
        - name: APPLY_CRD
          value: "true"
        - name: LOG_LEVEL
          value: debug
        - name: MAX_WORKERS
          value: "1"
        - name: CTX_TIMEOUT
          value: "300"
        - name: MELTDOWN_DURATION
          value: "60"
        - name: MELTDOWN_REQUEUE_AFTER
          value: "30"
        - name: MONITORED_ID
          value: cfo
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: quarks-secret
        image: index.docker.io/cfcontainerization/quarks-secret@sha256:4a3fbb75f4d767ed9e7c194a12d91f17a3eb3eb1392c1045cd0871579fc70dc4
        imagePullPolicy: IfNotPresent
        name: quarks-secret
        ports:
        - containerPort: 60000
          name: metrics
      serviceAccountName: cf-operator-quarks-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: v6.1.15-0.g89a56300
          Type: resolved
          URL: cfcontainerization/cf-operator:v6.1.15-0.g89a56300
        URL: index.docker.io/cfcontainerization/cf-operator@sha256:7c1217081bbc445578049de0fd4584b334e296cae8f66ff4aaf27e901ae31c56
  name: cf-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cf-operator
  template:
    metadata:
      labels:
        name: cf-operator
    spec:
      containers:
      - command:
        - cf-operator
        env:
        - name: APPLY_CRD
          value: "true"
        - name: BOSH_DNS_DOCKER_IMAGE
          value: cfcontainerization/coredns:0.1.0-1.6.7-bp152.1.19
        - name: CLUSTER_DOMAIN
          value: cluster.local
        - name: LOG_LEVEL
          value: debug
        - name: LOGROTATE_INTERVAL
          value: "1440"
        - name: MONITORED_ID
          value: cfo
        - name: CF_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CTX_TIMEOUT
          value: "300"
        - name: MELTDOWN_DURATION
          value: "60"
        - name: MELTDOWN_REQUEUE_AFTER
          value: "30"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: cf-operator
        - name: DOCKER_IMAGE_ORG
          value: cfcontainerization
        - name: DOCKER_IMAGE_REPOSITORY
          value: cf-operator
        - name: DOCKER_IMAGE_TAG
          value: v6.1.15-0.g89a56300
        - name: DOCKER_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: CF_OPERATOR_WEBHOOK_SERVICE_PORT
          value: "2999"
        - name: CF_OPERATOR_WEBHOOK_USE_SERVICE_REFERENCE
          value: "true"
        image: index.docker.io/cfcontainerization/cf-operator@sha256:7c1217081bbc445578049de0fd4584b334e296cae8f66ff4aaf27e901ae31c56
        imagePullPolicy: IfNotPresent
        name: cf-operator
        ports:
        - containerPort: 60000
          name: metrics
        - containerPort: 2999
          name: webhook
        readinessProbe:
          httpGet:
            path: /readyz
            port: 2999
            scheme: HTTPS
          initialDelaySeconds: 2
      serviceAccountName: cf-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cf-operator-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cf-operator-cluster
subjects:
- kind: ServiceAccount
  name: cf-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-operator-webhook
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cf-operator-webhook
subjects:
- kind: ServiceAccount
  name: cf-operator
  namespace: default
