---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
  - path: cluster/build/cluster-api/_vendir
    contents:
      - path: manual
        manual: {}
      - path: upstream/cluster-api
        githubRelease:
          slug: kubernetes-sigs/cluster-api
          tag: v0.3.8
          disableAutoChecksumValidation: true
        includePaths:
          - bootstrap-components.yaml
          - cluster-api-components.yaml
          - clusterctl-darwin-amd64
          - control-plane-components.yaml
          - core-components.yaml
