---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
  - path: deployments/cluster-api/build/_vendir
    contents:
      - path: github.com/kubernetes-sigs/cluster-api
        githubRelease:
          slug: kubernetes-sigs/cluster-api
          tag: v0.3.7
          disableAutoChecksumValidation: true
        includePaths:
          - bootstrap-components.yaml
          - cluster-api-components.yaml
          - clusterctl-darwin-amd64
          - control-plane-components.yaml
          - core-components.yaml
