# https://coolors.co/0f111a-23395b-406e8e-8ea8c3-cbf7ed-9a031e-cb793a-fcdc4d-ef9cda
# https://github.com/crazy-max/ghaction-github-labeler
---
- name: area/docs
  color: 0F111A
  description: changes to documentation
- name: area/deployment-mgmt
  color: 0F111A
  description: changes to workflows like helmfile, .github/**, etc.
- name: area/security
  color: 0F111A
  description: changes related to security
- name: area/networking
  color: 0F111A
  description: changes to istio, ingress, networking, etc.
- name: area/go-learn-about
  color: 0F111A
  description: something to go research and learn about

- name: foundation/iaas:aws
  color: 23395B
  description: related to aws
- name: foundation/iaas:docker
  color: 23395B
  description: related to docker

- name: foundation/region:us-east-2
  color: 406E8E
  description: related to us-east-2
- name: foundation/region:localhost
  color: 406E8E
  description: related to localhost

- name: foundation/env:sandbox
  color: 8EA8C3
  description: related to sandbox
- name: foundation/env:corp
  color: 8EA8C3
  description: related to corp
- name: foundation/env:kind
  color: 8EA8C3
  description: related to kind
- name: foundation/env:minikube
  color: 8EA8C3
  description: related to minikube

- name: deployment/cloudfoundry
  color: CBF7ED
  description: changes on cf-for-k8s, kubecf, stratos, harbor, etc.
- name: deployment/ci-cd
  color: CBF7ED
  description: changes on ci-cd systems like concourse, tektoncd, etc.
- name: deployment/auxillary
  color: CBF7ED
  description: changes on auxillary deployments like nginx-ingress, prometheus, etc.

- name: kind/bug
  color: 9A031E
  description: something isn't working
- name: kind/enhancement
  color: 9A031E
  description: an enhancement of an existing feature

- name: priority/just-a-thought
  color: CB793A
  description: what's lower than low? ice-low
- name: priority/low
  color: CB793A
  description: low priority
- name: priority/medium
  color: CB793A
  description: medium priority
- name: priority/high
  color: CB793A
  description: highest priority

- name: status/parking-lot
  color: FCDC4D
  description: on hold or soon to be abandonded
- name: status/probably-vaporware
  color: FCDC4D
  description: just goofing around with something or other

- name: wontfix
  color: EF9CDA
  description: this will not be worked on

- name: duplicate
  color: EF9CDA
  description: duplicate issue
