---
helmDefaults:
  kubeContext: kind-kind
  createNamespace: true
  recreatePods: false

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: ~2.8.x
    installed: true
    wait: true
    values:
      - config/ingress-nginx/values.yml
