---
version: "2"

tasks:
  install:
    cmds:
      - | # vendir sync
        kubectl apply --recursive --filename config/tektoncd-pipeline/vendor
        kubectl apply --recursive --filename config/tektoncd-pipeline/user-supplied-config

  start:
    cmds:
      - exit 1
      - |
        kubectl apply --filename config/tektoncd-pipeline/user-supplied-pipelines/echo.yaml
        tkn task start echo --dry-run
      - | # option 1 with kubectl...
        tkn task start echo --dry-run > taskRun.yaml
        kubectl create -f taskRun.yaml
      - | # option 2 with tkn cli
        tkn task start echo

  debug:
    cmds:
      - exit 1
      - |
        kubectl --namespace tekton-pipelines get pods --watch
