# https://github.com/kubernetes-sigs/kind/blob/master/pkg/internal/apis/config/encoding/testdata/v1alpha4/valid-many-fields.yaml
# https://github.com/kubernetes-sigs/kind/pull/637
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: worker
  - role: control-plane
    extraPortMappings:
      - containerPort: 32080
        hostPort: 80
      - containerPort: 32443
        hostPort: 443
      # for use with yugabyte
      - containerPort: 7000
        hostPort: 7000
      - containerPort: 9042
        hostPort: 9042
      - containerPort: 6379
        hostPort: 6379
      - containerPort: 5433
        hostPort: 5433
