---
version: "2"

tasks:
  kind-trust-k8s-root-ca-on-docker-daemon:
    cmds: # https://github.com/cloudfoundry-incubator/cf-operator/#prerequisites
      - |
        docker exec -it "kind-control-plane" bash -c 'cp /etc/kubernetes/pki/ca.crt /etc/ssl/certs/ && update-ca-certificates && (systemctl list-units | grep containerd > /dev/null && systemctl restart containerd)'

  kind-create:
    cmds:
      - kind create cluster --config kind.config.yaml # --image kindest/node:v1.17.5
      - task: kind-trust-k8s-root-ca-on-docker-daemon

  kind-delete:
    cmds:
      - |
        kind delete cluster
        docker system prune --all --volumes --force
