---
version: "2"

tasks:
  kind-create:
    cmds:
      - kind create cluster --config kind.config.yaml --image kindest/node:v1.16.3

  kind-delete:
    cmds:
      - kind delete cluster
      - docker system prune --all --volumes --force
