# https://cert-manager.io/docs/configuration/acme/dns01/route53/
# https://cert-manager.io/docs/usage/certificate/
---
apiVersion: v1
kind: Namespace
metadata:
  name: letsencrypt-staging
  labels:
    istio-injection: disabled

---
apiVersion: cert-manager.io/v1beta1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: letsencrypt-staging
spec:
  acme:
    email: aegershman+letsencrypt@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          route53:
            region: us-east-2

---
apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: cf-gershman-io-staging
  namespace: letsencrypt-staging
spec:
  secretName: letsencrypt-cert-tls-cf-gershman-io-staging
  dnsNames:
    - "*.cf.gershman.io"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Never # Always
