kube:
  auth: "rbac"

  storage_class:
    persistent: "standard"
    shared: "standard"

services:
  loadbalanced: false

ingress:
  enabled: true
  tls:
    crt: ~
    key: ~

env:
  DOMAIN: eirini.127.0.0.1.xip.io
  UAA_HOST: uaa.eirini.127.0.0.1.xip.io
  UAA_PORT: "443"
