# https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/all-in-one-with-options.yaml
---
jaeger:
  create: true
  spec:
    strategy: allInOne
    allInOne:
      options:
        log-level: debug
    ingress:
      enabled: true
      hosts:
        - jaeger.vcap.me
