postgresql:
  enabled: true
  persistence:
    enabled: true
    size: 8Gi

worker:
  replicas: 1

persistence:
  worker:
    size: 20Gi

web:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - concourse.gershman.io

concourse:
  web:
    externalUrl: http://concourse.gershman.io
    localAuth:
      enabled: false
    kubernetes:
      enabled: false
    auth:
      mainTeam:
        github:
          user: aegershman
      github:
        enabled: true
