# https://github.com/weaveworks/eksctl/tree/master/examples
# https://eksctl.io/usage/schema/
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aegershman-example-0
  region: us-east-2
  version: "1.17"
  tags: {}

vpc:
  nat:
    gateway: Single # Disable, Single (default), HighlyAvailable

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    availabilityZones:
      - us-east-2a
      - us-east-2b
      - us-east-2c
    desiredCapacity: 1
    volumeSize: 80
    labels:
      somelabelkey: some-label-value
    privateNetworking: false # if only 'private' subnets are given, this must be enabled
    tags: {}
    iam:
      withAddonPolicies:
        albIngress: true
        certManager: true
        elb: true
        externalDNS: true
