---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aegershman-example-0
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
