---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
  - path: deployments/cf-for-k8s/build/_vendir
    contents:
      - path: github.com/cloudfoundry/cf-for-k8s
        git:
          url: https://github.com/cloudfoundry/cf-for-k8s
          ref: b892ece915d5968a312e0abe6d37cca9a1520d60 # beyond v0.4.0
        includePaths:
          - config-optional/**/*
          - config/**/*
          - hack/generate-values.sh
          - tests/smoke/assets/test-node-app/**/*
  - path: deployments/external-dns/build/_vendir/external-dns
    contents:
      - path: .
        git:
          url: https://github.com/bitnami/charts
          ref: a0d9242d3aa21296ffe0584e5eda478bcc961ea7 # 3.2.4
          disableAutoChecksumValidation: true
        includePaths:
          - bitnami/external-dns/**/*
