---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
  - path: cluster/build/cf-for-k8s/_vendir
    contents:
      - path: .
        git:
          url: https://github.com/cloudfoundry/cf-for-k8s
          ref: b892ece915d5968a312e0abe6d37cca9a1520d60 # beyond v0.4.0
        includePaths:
          - config-optional/**/*
          - config/**/*
          - hack/generate-values.sh
          - tests/smoke/assets/test-node-app/**/*
  - path: cluster/build/external-dns/_vendir
    contents:
      - path: .
        git:
          url: https://github.com/bitnami/charts
          ref: a0d9242d3aa21296ffe0584e5eda478bcc961ea7 # 3.2.4
          disableAutoChecksumValidation: true
        includePaths:
          - bitnami/external-dns/**/*
  - path: cluster/build/harbor/_vendir
    contents:
      - path: .
        git:
          url: https://github.com/goharbor/harbor-helm
          ref: 768a3b2c03bcb708fc7c2bfc6b9552437efff067 # 1.3.4
          disableAutoChecksumValidation: true
        includePaths:
          - cert/**/*
          - conf/**/*
          - templates/**/*
          - .helmignore
          - Chart.yaml
          - LICENSE
          - README.md
          - values.yaml
