---
variables:
  - name: cf_admin_password
    type: password
  - name: blobstore_secret_key
    type: password
  - name: db_admin_password
    type: password
  - name: capi_db_password
    type: password
  - name: uaa_db_password
    type: password
  - name: uaa_admin_client_secret
    type: password
  - name: uaa_encryption_key_passphrase
    type: password
  - name: default_ca
    type: certificate
    options:
      is_ca: true
      common_name: ca
  - name: system_certificate
    type: certificate
    options:
      ca: default_ca
      common_name: "*.${DOMAIN}"
      alternative_names:
        - "*.login.${DOMAIN}"
        - "*.uaa.${DOMAIN}"
      extended_key_usage:
        - server_auth
  - name: workloads_certificate
    type: certificate
    options:
      ca: default_ca
      common_name: "*.apps.${DOMAIN}"
      extended_key_usage:
        - server_auth
  - name: internal_certificate
    type: certificate
    options:
      ca: default_ca
      common_name: "*.cf-system.svc.cluster.local"
      extended_key_usage:
        - client_auth
        - server_auth

  - name: uaa_jwt_policy_signing_key
    type: certificate
    options:
      ca: default_ca
      common_name: uaa_jwt_policy_signing_key

  - name: uaa_login_service_provider
    type: certificate
    options:
      ca: default_ca
      common_name: uaa_login_service_provider

  - name: log_cache_ca
    type: certificate
    options:
      is_ca: true
      common_name: log-cache-ca

  - name: log_cache
    type: certificate
    options:
      ca: log_cache_ca
      common_name: log-cache
      extended_key_usage:
        - client_auth
        - server_auth

  - name: log_cache_syslog
    type: certificate
    options:
      ca: log_cache_ca
      common_name: log-cache-syslog
      extended_key_usage:
        - client_auth
        - server_auth

  - name: log_cache_metrics
    type: certificate
    options:
      ca: log_cache_ca
      common_name: log-cache-metrics
      extended_key_usage:
        - client_auth
        - server_auth

  - name: log_cache_gateway
    type: certificate
    options:
      ca: log_cache_ca
      common_name: log-cache-gateway
      alternative_names:
        - localhost
      extended_key_usage:
        - client_auth
        - server_auth

  - name: metric_proxy_ca
    type: certificate
    options:
      is_ca: true
      common_name: metric-proxy-ca

  - name: metric_proxy
    type: certificate
    options:
      ca: metric_proxy_ca
      common_name: metric-proxy
      extended_key_usage:
        - client_auth
        - server_auth
