---
apiVersion: gluon.starkandwayne.com/v1alpha1
kind: BOSHDeployment
metadata:
  name: glosh1

spec:
  repo: https://github.com/cloudfoundry/bosh-deployment
  ops:
    - uaa
    - credhub
    - vsphere/cpi

  vars:
    - configMap:
        name: bosh-gluon-glosh
    - secret:
        name: buffalo-lab-vcenter
    - name: internal_ip
      value: 10.0.0.4
