---
apiVersion: v1
kind: ConfigMap
metadata:
  name: buffalo-lab-boshes

data:
  vcenter_ip: your.vsphere.example.com
  vcenter_dc: dc1
  vcenter_cluster: cluster1
  vcenter_ds: store1

  internal_cidr: 10.0.0.0/8
  internal_gw: 10.0.0.1

  network_name: VM Network

  vcenter_disks: gluon/demo/disks
  vcenter_templates: gluon/demo/templates
  vcenter_vms: gluon/demo/vms
