#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")

---
apiVersion: v1
kind: Namespace
metadata:
  name: quarks-secret
  labels:
    istio-injection: enabled
    quarks.cloudfoundry.org/monitored: cf-quarks-secret

--- #@ template.replace(library.get("quarks-secret").eval())
