---
version: "2"

tasks:
  install:
    cmds:
      - | # vendir sync
        kubectl apply --recursive --filename config/tektoncd/vendor

  debug:
    cmds:
      - exit 1
      - |
        kubectl --namespace tekton-pipelines get pods --watch
