---
version: "2"

tasks:
  apply:
    cmds:
      - | # vendir sync
        kubectl apply --recursive --filename config/tektoncd/vendor
        kubectl apply --recursive --filename config/tektoncd/user-supplied-config
      - |
        kubectl apply --filename config/tektoncd/user-supplied-pipelines/echo.yaml

  debug:
    cmds:
      - exit 1
      - |
        kubectl --namespace tekton-pipelines get pods --watch
