---
applications:
  - name: todo-ui
    instances: 1
    memory: 256M
    routes:
      - route: todo.kubecf.vcap.me
    docker:
      image: dbbaskette/todos-ui
    metadata:
      annotations:
        prometheus.io/scrape: "false"
