---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: yb-master-pdb
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: yb-master
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: yb-tserver-pdb
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: yb-tserver
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yb-master
    chart: yugabyte
    component: yugabytedb
    heritage: Helm
    release: yugabyte
    service-type: headless
  name: yb-masters
spec:
  clusterIP: None
  ports:
  - name: rpc-port
    port: 7100
  - name: ui
    port: 7000
  selector:
    app: yb-master
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yb-tserver
    chart: yugabyte
    component: yugabytedb
    heritage: Helm
    release: yugabyte
    service-type: headless
  name: yb-tservers
spec:
  clusterIP: None
  ports:
  - name: rpc-port
    port: 7100
  - name: ui
    port: 9000
  - name: ycql-metrics
    port: 12000
  - name: yedis-metrics
    port: 11000
  - name: yedis-port
    port: 6379
  - name: yql-port
    port: 9042
  - name: ysql-metrics
    port: 13000
  - name: ysql-port
    port: 5433
  selector:
    app: yb-tserver
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: "1.31"
          Type: resolved
          URL: busybox:1.31
        URL: index.docker.io/library/busybox@sha256:95cf004f559831017cdf4628aaf1bb30133677be8702a8c5f2994629f637a209
      - Metas:
        - Tag: 2.2.2.0-b15
          Type: resolved
          URL: yugabytedb/yugabyte:2.2.2.0-b15
        URL: index.docker.io/yugabytedb/yugabyte@sha256:c0f92818c459f47a89f2f45a71af5702d26c6ff312af346c96f2579524cc5914
  labels:
    app: yb-master
    chart: yugabyte
    component: yugabytedb
    heritage: Helm
    release: yugabyte
  name: yb-master
  namespace: default
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: yb-master
  serviceName: yb-masters
  template:
    metadata:
      labels:
        app: yb-master
        chart: yugabyte
        component: yugabytedb
        heritage: Helm
        release: yugabyte
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - yb-master
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - /home/yugabyte/bin/yb-master
        - --fs_data_dirs=/mnt/disk0
        - --rpc_bind_addresses=$(HOSTNAME).yb-masters.$(NAMESPACE).svc.cluster.local
        - --server_broadcast_addresses=$(HOSTNAME).yb-masters.$(NAMESPACE).svc.cluster.local:7100
        - --master_addresses= yb-master-0.yb-masters.$(NAMESPACE).svc.cluster.local:7100
        - --replication_factor=1
        - --enable_ysql=true
        - --metric_node_name=$(HOSTNAME)
        - --memory_limit_hard_bytes=1824522240
        - --stderrthreshold=0
        - --num_cpus=0
        - --undefok=num_cpus,enable_ysql
        - --default_memory_limit_to_ram_ratio=0.85
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: index.docker.io/yugabytedb/yugabyte@sha256:c0f92818c459f47a89f2f45a71af5702d26c6ff312af346c96f2579524cc5914
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - |
                mkdir -p /mnt/disk0/cores; mkdir -p /mnt/disk0/yb-data/scripts; if [ ! -f /mnt/disk0/yb-data/scripts/log_cleanup.sh ]; then
                  if [ -f /home/yugabyte/bin/log_cleanup.sh ]; then
                    cp /home/yugabyte/bin/log_cleanup.sh /mnt/disk0/yb-data/scripts;
                  fi;
                fi
        name: yb-master
        ports:
        - containerPort: 7100
          name: rpc-port
        - containerPort: 7000
          name: ui
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /mnt/disk0
          name: datadir0
        workingDir: /mnt/disk0
      - command:
        - /bin/sh
        - -c
        - |
          mkdir /var/spool/cron; mkdir /var/spool/cron/crontabs; echo "0 * * * * /home/yugabyte/scripts/log_cleanup.sh" | tee -a /var/spool/cron/crontabs/root; crond; while true; do
            sleep 86400;
          done
        env:
        - name: USER
          value: yugabyte
        image: index.docker.io/library/busybox@sha256:95cf004f559831017cdf4628aaf1bb30133677be8702a8c5f2994629f637a209
        name: yb-cleanup
        volumeMounts:
        - mountPath: /home/yugabyte/
          name: datadir0
          subPath: yb-data
      volumes:
      - hostPath:
          path: /mnt/disks/ssd0
        name: datadir0
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
      labels:
        chart: yugabyte
        component: yugabytedb
        heritage: Helm
        release: yugabyte
      name: datadir0
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2G
      storageClassName: standard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: "1.31"
          Type: resolved
          URL: busybox:1.31
        URL: index.docker.io/library/busybox@sha256:95cf004f559831017cdf4628aaf1bb30133677be8702a8c5f2994629f637a209
      - Metas:
        - Tag: 2.2.2.0-b15
          Type: resolved
          URL: yugabytedb/yugabyte:2.2.2.0-b15
        URL: index.docker.io/yugabytedb/yugabyte@sha256:c0f92818c459f47a89f2f45a71af5702d26c6ff312af346c96f2579524cc5914
  labels:
    app: yb-tserver
    chart: yugabyte
    component: yugabytedb
    heritage: Helm
    release: yugabyte
  name: yb-tserver
  namespace: default
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: yb-tserver
  serviceName: yb-tservers
  template:
    metadata:
      labels:
        app: yb-tserver
        chart: yugabyte
        component: yugabytedb
        heritage: Helm
        release: yugabyte
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - yb-tserver
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - /home/yugabyte/bin/yb-tserver
        - --fs_data_dirs=/mnt/disk0
        - --server_broadcast_addresses=$(HOSTNAME).yb-tservers.$(NAMESPACE).svc.cluster.local:9100
        - --rpc_bind_addresses=$(HOSTNAME).yb-tservers.$(NAMESPACE).svc.cluster.local
        - --cql_proxy_bind_address=$(HOSTNAME).yb-tservers.$(NAMESPACE).svc.cluster.local
        - --enable_ysql=true
        - --pgsql_proxy_bind_address=$(POD_IP):5433
        - --tserver_master_addrs= yb-master-0.yb-masters.$(NAMESPACE).svc.cluster.local:7100
        - --metric_node_name=$(HOSTNAME)
        - --memory_limit_hard_bytes=3649044480
        - --stderrthreshold=0
        - --num_cpus=0
        - --undefok=num_cpus,enable_ysql
        - --use_cassandra_authentication=false
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: index.docker.io/yugabytedb/yugabyte@sha256:c0f92818c459f47a89f2f45a71af5702d26c6ff312af346c96f2579524cc5914
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - |
                mkdir -p /mnt/disk0/cores; mkdir -p /mnt/disk0/yb-data/scripts; if [ ! -f /mnt/disk0/yb-data/scripts/log_cleanup.sh ]; then
                  if [ -f /home/yugabyte/bin/log_cleanup.sh ]; then
                    cp /home/yugabyte/bin/log_cleanup.sh /mnt/disk0/yb-data/scripts;
                  fi;
                fi
        name: yb-tserver
        ports:
        - containerPort: 7100
          name: rpc-port
        - containerPort: 9000
          name: ui
        - containerPort: 12000
          name: ycql-metrics
        - containerPort: 11000
          name: yedis-metrics
        - containerPort: 6379
          name: yedis-port
        - containerPort: 9042
          name: yql-port
        - containerPort: 13000
          name: ysql-metrics
        - containerPort: 5433
          name: ysql-port
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /mnt/disk0
          name: datadir0
        workingDir: /mnt/disk0
      - command:
        - /bin/sh
        - -c
        - |
          mkdir /var/spool/cron; mkdir /var/spool/cron/crontabs; echo "0 * * * * /home/yugabyte/scripts/log_cleanup.sh" | tee -a /var/spool/cron/crontabs/root; crond; while true; do
            sleep 86400;
          done
        env:
        - name: USER
          value: yugabyte
        image: index.docker.io/library/busybox@sha256:95cf004f559831017cdf4628aaf1bb30133677be8702a8c5f2994629f637a209
        name: yb-cleanup
        volumeMounts:
        - mountPath: /home/yugabyte/
          name: datadir0
          subPath: yb-data
      volumes:
      - hostPath:
          path: /mnt/disks/ssd0
        name: datadir0
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
      labels:
        chart: yugabyte
        component: yugabytedb
        heritage: Helm
        release: yugabyte
      name: datadir0
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2G
      storageClassName: standard
