# export KUBECONFIG="$(kind get kubeconfig-path)"

version: "2"

env:
  KUBECONFIG:
    sh: kind get kubeconfig-path

tasks:
  create:
    cmds:
      - kind create cluster --config bootstrap/kind.config.yaml
      - task: bootstrap
      - task: sync

  bootstrap:
    cmds:
      - kubectl apply -f bootstrap/rbac-tiller.yml
      - helm init --service-account tiller --upgrade --wait

  delete:
    cmds:
      - kind delete cluster
      - docker system prune --all --volumes --force

  sync:
    cmds:
      - helmfile sync
