# https://github.com/kubernetes/ingress-nginx/blob/1ba39f508817605a92443ebfcaf084029ec94f44/charts/ingress-nginx/values.yaml#L37
# https://github.com/kubernetes/ingress-nginx/issues/3268
# https://github.com/kubernetes/ingress-nginx/issues/4360
# https://github.com/kubernetes/ingress-nginx/issues/5401
# https://kubernetes.github.io/ingress-nginx/deploy/baremetal/#via-the-host-network
---
controller:
  replicaCount: 1
  service:
    type: NodePort
  config:
    enable-opentracing: "true"
    jaeger-collector-host: jaeger-operator-jaeger-agent.jaeger-operator.svc.cluster.local
    jaeger-collector-port: "6831"
    jaeger-service-name: nginx
    proxy-body-size: 64m
    proxy-buffer-size: 16k
  metrics:
    enabled: true
    service:
      type: ClusterIP
    serviceMonitor:
      enabled: true
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  terminationGracePeriodSeconds: 300

  admissionWebhooks:
    enabled: true
    failurePolicy: Fail
    port: 8443
    service:
      servicePort: 443
      type: ClusterIP

defaultBackend:
  enabled: false

tcp:
  20000: kubecf/tcp-router:20000"
  20001: kubecf/tcp-router:20001"
  20002: kubecf/tcp-router:20002"
  20003: kubecf/tcp-router:20003"
  20004: kubecf/tcp-router:20004"
  20005: kubecf/tcp-router:20005"
  20006: kubecf/tcp-router:20006"
  20007: kubecf/tcp-router:20007"
  20008: kubecf/tcp-router:20008"
  2222: "kubecf/scheduler:2222"
