# https://github.com/kubernetes/ingress-nginx/issues/5401
---
controller:
  replicaCount: 1
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    type: NodePort
  config:
    proxy-body-size: 64m
    proxy-buffer-size: 16k
  metrics:
    enabled: false
    service:
      type: ClusterIP
    serviceMonitor:
      enabled: false
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  terminationGracePeriodSeconds: 20

defaultBackend:
  enabled: false

tcp:
  20000: kubecf/tcp-router:20000"
  20001: kubecf/tcp-router:20001"
  20002: kubecf/tcp-router:20002"
  20003: kubecf/tcp-router:20003"
  20004: kubecf/tcp-router:20004"
  20005: kubecf/tcp-router:20005"
  20006: kubecf/tcp-router:20006"
  20007: kubecf/tcp-router:20007"
  20008: kubecf/tcp-router:20008"
  2222: "kubecf/scheduler:2222"
