# https://eksctl.io/usage/schema/
# https://github.com/weaveworks/eksctl/tree/master/examples
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cf-for-k8s-demo
  region: us-east-2
  version: "1.17"
  tags: { cost-center: aegershman }

vpc:
  autoAllocateIPv6: false
  nat:
    gateway: Single
  clusterEndpoints:
    publicAccess: true
    privateAccess: false

nodeGroups:
  - name: ng-0
    instanceType: m5.large
    desiredCapacity: 3
    minSize: 1
    maxSize: 5
    volumeSize: 80
    labels: {}
    tags: { cost-center: aegershman }
    iam:
      withAddonPolicies:
        albIngress: false
        appMesh: false
        appMeshPreview: false
        autoScaler: false
        certManager: true
        cloudWatch: false
        ebs: true
        efs: false
        externalDNS: true
        fsx: false
        imageBuilder: true
    volumeType: gp2
    volumeEncrypted: true

cloudWatch:
  clusterLogging:
    enableTypes: []

secretsEncryption:
  keyARN: "arn:aws:kms:us-east-2:450544694753:key/bbd7c971-c83d-4534-a9d9-f173f070cba6"
