---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
  - path: cluster/build/cert-manager/_vendir
    contents:
      - path: manual
        manual: {}
      - path: upstream
        githubRelease:
          slug: jetstack/cert-manager
          tag: v1.1.0
          disableAutoChecksumValidation: true
        includePaths:
          - cert-manager.yaml
          - kubectl-cert_manager-darwin-amd64.tar.gz
  - path: cluster/build/cf-for-k8s/_vendir
    contents:
      - path: manual
        manual: {}
      - path: upstream/cf-for-k8s
        git:
          url: https://github.com/cloudfoundry/cf-for-k8s
          ref: c72740e81a15fa9c386578e75853fcc43e8f014e # beyond v1.0.0
        includePaths:
          - config/**/*
          - hack/generate-values.sh
          - tests/smoke/assets/test-node-app/**/*
  - path: cluster/build/external-dns/_vendir
    contents:
      - path: manual
        manual: {}
      - path: upstream
        git:
          url: https://github.com/bitnami/charts
          ref: 0966de9fb6f693aea277d1c79fd8f43c3e65b897 # 3.4.6
        includePaths:
          - bitnami/external-dns/**/*
  - path: cluster/build/harbor/_vendir
    contents:
      - path: manual
        manual: {}
      - path: upstream/harbor-helm
        git:
          url: https://github.com/goharbor/harbor-helm
          ref: tags/v1.3.6
        excludePaths:
          - .git/**/*
          - docs/**/*
          - test/**/*
  - path: cluster/build/quarks-secret/_vendir
    contents:
      - path: manual
        manual: {}
      - path: upstream
        git:
          url: https://github.com/cloudfoundry-incubator/quarks-secret
          ref: tags/v1.0.744
        includePaths:
          - deploy/helm/quarks-secret/**/*
  - path: cluster/build/secretgen-controller/_vendir
    contents:
      - path: manual
        manual: {}
      - path: upstream
        githubRelease:
          slug: vmware-tanzu/carvel-secretgen-controller
          tag: v0.2.0
          disableAutoChecksumValidation: false
        includePaths:
          - release.yml

  # the components in this section below are handled by their corresponding build scripts
  # the manual param tells vendir to not override/touch the contents of these directories
  - path: cluster/config/cert-manager/_ytt_lib
    contents:
      - path: cert-manager
        manual: {}
  - path: cluster/config/cf-for-k8s/_ytt_lib
    contents:
      - path: cf-for-k8s
        manual: {}
  - path: cluster/config/external-dns/_ytt_lib
    contents:
      - path: external-dns
        manual: {}
  - path: cluster/config/harbor/_ytt_lib
    contents:
      - path: harbor
        manual: {}
  - path: cluster/config/quarks-secret/_ytt_lib
    contents:
      - path: quarks-secret
        manual: {}
  - path: cluster/config/secretgen-controller/_ytt_lib
    contents:
      - path: secretgen-controller
        manual: {}
