---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
  - path: cluster/build/cert-manager/_vendir
    contents:
      - path: .
        githubRelease:
          slug: jetstack/cert-manager
          tag: v0.16.0
          disableAutoChecksumValidation: true
        includePaths:
          - cert-manager.yaml
          - kubectl-cert_manager-darwin-amd64.tar.gz
  - path: cluster/build/cf-for-k8s/_vendir/cf-for-k8s
    contents:
      - path: .
        git:
          url: https://github.com/cloudfoundry/cf-for-k8s
          ref: 924eeab0031c127a1644e4f2a63f262f577bb927 # beyond v0.4.0
        includePaths:
          - config-optional/**/*
          - config/**/*
          - hack/generate-values.sh
          - tests/smoke/assets/test-node-app/**/*
  - path: cluster/build/external-dns/_vendir
    contents:
      - path: .
        git:
          url: https://github.com/bitnami/charts
          ref: a0d9242d3aa21296ffe0584e5eda478bcc961ea7 # 3.2.4
        includePaths:
          - bitnami/external-dns/**/*
  - path: cluster/build/harbor/_vendir/harbor-helm
    contents:
      - path: .
        git:
          url: https://github.com/goharbor/harbor-helm
          ref: tags/v1.3.4
        includePaths:
          - cert/**/*
          - conf/**/*
          - templates/**/*
          - .helmignore
          - Chart.yaml
          - LICENSE
          - README.md
          - values.yaml

  # the components in this section below are handled by their corresponding build scripts
  # the manual param tells vendir to not override/touch the contents of these directories
  - path: cluster/config/cert-manager/_ytt_lib
    contents:
      - path: cert-manager
        manual: {}
  - path: cluster/config/cf-for-k8s/_ytt_lib
    contents:
      - path: cf-for-k8s
        manual: {}
  - path: cluster/config/external-dns/_ytt_lib
    contents:
      - path: external-dns
        manual: {}
  - path: cluster/config/harbor/_ytt_lib
    contents:
      - path: harbor
        manual: {}
