---
controller:
  replicaCount: 1
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    type: NodePort
  config:
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
    proxy-body-size: 64m
    proxy-buffer-size: 16k

defaultBackend:
  enabled: false

# https://github.com/SUSE/kubecf/blob/master/deploy/helm/kubecf/values.yaml#L101-L103
# https://github.com/SUSE/kubecf/blob/master/doc/dev/general.md#installation-of-the-nginx-ingress-controller
tcp:
  20000: kubecf/kubecf-tcp-router:20000"
  20001: kubecf/kubecf-tcp-router:20001"
  20002: kubecf/kubecf-tcp-router:20002"
  20003: kubecf/kubecf-tcp-router:20003"
  20004: kubecf/kubecf-tcp-router:20004"
  20005: kubecf/kubecf-tcp-router:20005"
  20006: kubecf/kubecf-tcp-router:20006"
  20007: kubecf/kubecf-tcp-router:20007"
  20008: kubecf/kubecf-tcp-router:20008"
  2222: "kubecf/kubecf-scheduler:2222"
