---
applications:
  - name: todo-ui
    instances: 1
    memory: 256M
    routes:
      - route: todo.apps.vcap.me
      - route: todo.vcap.me
    docker:
      image: dbbaskette/todos-ui
    metadata:
      annotations:
        prometheus.io/scrape: "false"
