---
apiVersion: v1
kind: Secret
metadata:
  name: basic-docker-user-pass
  annotations:
    build.pivotal.io/docker: docker.pkg.github.com
type: kubernetes.io/basic-auth
stringData:
  username: aegershman
  password: xyz # TODO
