#@ load("@ytt:library", "library")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")

#@ def add_prometheus_operator_namespace():
#@overlay/match by=overlay.all, expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  namespace: prometheus-operator
#@ end

---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-operator
  labels:
    istio-injection: enabled

--- #@ template.replace(overlay.apply(library.get("prometheus-operator").eval(), add_prometheus_operator_namespace()))
