---
helmDefaults:
  kubeContext: kind-kind

repositories:
  - name: quarks
    url: https://cloudfoundry-incubator.github.io/quarks-helm
  - name: stratos
    url: https://cloudfoundry.github.io/stratos

releases:
  - name: cf-operator
    chart: quarks/cf-operator
    version: ~4.3.x
    installed: true
    wait: true
    values:
      - config/cf-operator/values.yml

  - name: kubecf
    namespace: kubecf
    chart: https://github.com/cloudfoundry-incubator/kubecf/releases/download/v2.0.0/kubecf-v2.0.0.tgz
    installed: true
    needs:
      - cf-operator
      - nginx
    values:
      - config/kubecf/values.yml

  - name: nginx
    chart: stable/nginx-ingress
    installed: true
    version: ~1.x.x
    values:
      - config/nginx/values.yml

  - name: stratos
    chart: stratos/console
    installed: false
    version: ~3.0.x
    needs:
      - kubecf/kubecf
      - nginx
    values:
      - config/stratos/values.yml
