---
helmDefaults:
  kubeContext: kind-kind

repositories:
  - name: minibroker
    url: https://minibroker.blob.core.windows.net/charts
  - name: quarks
    url: https://cloudfoundry-incubator.github.io/quarks-helm
  - name: stratos
    url: https://cloudfoundry.github.io/stratos

releases:
  - name: cf-operator
    namespace: cf-operator
    createNamespace: true
    chart: quarks/cf-operator
    version: ~4.4.x
    installed: true
    wait: true
    values:
      - config/cf-operator/values.yml

  - name: kubecf
    namespace: kubecf
    chart: https://github.com/cloudfoundry-incubator/kubecf/releases/download/v2.1.0/kubecf-v2.1.0.tgz
    installed: true
    needs:
      - cf-operator/cf-operator
      - nginx-ingress/nginx
    values:
      - config/kubecf/values.yml

  - name: minibroker
    namespace: minibroker
    createNamespace: true
    chart: minibroker/minibroker
    installed: true
    version: ~0.x.x
    needs:
      - kubecf/kubecf
    values:
      - config/minibroker/values.yml

  - name: nginx
    namespace: nginx-ingress
    createNamespace: true
    chart: stable/nginx-ingress
    installed: true
    version: ~1.x.x
    values:
      - config/nginx/values.yml

  - name: stratos
    chart: stratos/console
    installed: false
    version: ~3.1.x
    needs:
      - kubecf/kubecf
      - nginx-ingress/nginx
    values:
      - config/stratos/values.yml
