---
helmDefaults:
  kubeContext: kind-kind

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: minibroker
    url: https://minibroker.blob.core.windows.net/charts
  - name: quarks
    url: https://cloudfoundry-incubator.github.io/quarks-helm
  - name: stratos
    url: https://cloudfoundry.github.io/stratos

releases:
  - name: cf-operator
    namespace: cf-operator
    createNamespace: true
    chart: quarks/cf-operator
    version: 4.5.6
    installed: true
    wait: true
    values:
      - config/cf-operator/values.yml

  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    installed: true
    version: ~2.1.x
    wait: true
    values:
      - config/ingress-nginx/values.yml

  - name: kubecf
    namespace: kubecf
    chart: https://github.com/cloudfoundry-incubator/kubecf/releases/download/v2.2.0/kubecf-v2.2.0.tgz
    installed: true
    needs:
      - cf-operator/cf-operator
      - ingress-nginx/ingress-nginx
    values:
      - config/kubecf/values.yml

  - name: minibroker
    namespace: minibroker
    createNamespace: true
    chart: minibroker/minibroker
    installed: true
    version: ~0.x.x
    values:
      - config/minibroker/values.yml

  - name: stratos
    namespace: stratos
    createNamespace: true
    chart: stratos/console
    installed: false
    version: ~3.1.x
    needs:
      - kubecf/kubecf
      - ingress-nginx/ingress-nginx
    values:
      - config/stratos/values.yml
