---
helmDefaults:
  kubeContext: kind-kind

repositories:
  - name: quarks
    url: https://cloudfoundry-incubator.github.io/quarks-helm
  - name: stratos
    url: https://cloudfoundry.github.io/stratos

# https://cf-operators.s3.amazonaws.com/helm-charts/index.html
# https://github.com/cloudfoundry-incubator/cf-operator/blob/master/deploy/helm/cf-operator/values.yaml
# https://github.com/cloudfoundry-incubator/cf-operator/blob/master/dev-env-kind.yaml
# https://github.com/cloudfoundry-incubator/cf-operator/releases
# https://github.com/cloudfoundry-incubator/kubecf-docs/blob/master/content/en/docs/Getting%20started/kubernetes-deploy.md
# https://github.com/cloudfoundry-incubator/kubecf/blob/master/deploy/helm/kubecf/values.yaml
# https://github.com/cloudfoundry-incubator/kubecf/blob/master/dev/kind/config.yaml
# https://github.com/cloudfoundry/cf-for-k8s/blob/master/deploy/kind/cluster.yml
# https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/deploy.md
# https://github.com/cloudfoundry/stratos/blob/master/deploy/kubernetes/console/values.yaml
# https://github.com/SUSE/kubecf/blob/master/doc/dev/general.md
# https://github.com/SUSE/kubecf/blob/master/doc/dev/minikube.md
# https://kubecf.suse.dev/docs/tutorials/deploy-kind/
# https://scf-v3.s3.amazonaws.com/index.html
releases:
  - name: cf-operator
    chart: quarks/cf-operator
    version: ~3.4.x
    installed: true
    wait: true
    values:
      - config/cf-operator/values.yml

  - name: kubecf
    namespace: kubecf
    chart: https://github.com/cloudfoundry-incubator/kubecf/releases/download/v1.0.1/kubecf-v1.0.1.tgz
    installed: true
    needs:
      - cf-operator
      - nginx
    values:
      - config/kubecf/values.yml

  - name: nginx
    chart: stable/nginx-ingress
    installed: true
    version: ~1.x.x
    values:
      - config/nginx/values.yml

  - name: stratos
    chart: stratos/console
    installed: false
    version: ~3.0.x
    needs:
      - kubecf/kubecf
      - nginx
    values:
      - config/stratos/values.yml
