---
version: "2"

tasks:
  rm-crds:
    cmds:
      - kubectl delete crd boshdeployments.quarks.cloudfoundry.org quarksjobs.quarks.cloudfoundry.org quarkssecrets.quarks.cloudfoundry.org quarksstatefulsets.quarks.cloudfoundry.org
