#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")

---
apiVersion: v1
kind: Namespace
metadata:
  name: secretgen-controller
  labels:
    istio-injection: disabled

--- #@ template.replace(library.get("secretgen-controller").eval())
