kubecostToken: ENC[AES256_GCM,data:d0yhDU0EklZ+/CRRAxFgTh6yU/ZMH+t65W6VI2Ks+cBF026Y0BZ0k4JKr7sQGlTowTVf,iv:YDhm837xWMZmcDmSsmVTMlc00C8EhSm02mQr0e2tR7I=,tag:Rcq0C/TbgT3ORYyXcU0N/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-07-19T05:24:43Z'
    mac: ENC[AES256_GCM,data:/sCQCkaQ5x51z9RyxRXL3EPzRI7Cd2o1pVjz/YJ4fsoA7UFiZArNHbkFbnVg9Dx3ITRKXL51GYTR3Ngu3ftvywUVKNfEuVVBvkd+Uulqi6r8w9MrIBWSNZSkn4SNpbNbfIppahhNB98DvoXCypjn9fyANkRT0rvXQuPvHNmn/XY=,iv:qi0R4dpe0ZfFdiv8U7skhnJl7MQFeqiJdKovS678yTw=,tag:sYKFEgOJVRN/XvVJRAzfJg==,type:str]
    pgp:
    -   created_at: '2019-07-19T05:24:41Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8UfoNGH8bXiAQ/9FtXjXVwU5UinqK7gJS1xrkqpXE+8zFkYUI2Tmeq3dgDN
            2klpSx0FRFybSQW/xPHLW86HMoS7yPAZcVSnbATTUcr6vNx99XrPqXp/Z/yuLZj0
            UYgsVw5Bx1lrEXWP1MjwqkYrWRQfAcG9DnBOmbqqPNRMq0QWZRHvMvLG4G+GMlK9
            XcgJn2s1XgBxTANG8FkUZXySQsD+ToOn2hjme4dxClziTNH1USGKJO2ur6SEq25O
            Z06AmiSodKjY9y/MaEcTP1gtKp6YSOaoMXjOp309vsy6XLaUkk7TqmE2r3mLKE+P
            IYp7ElMb1M8gkPWl8EfXua5zO5YZEFN3jQnT6iw9fDPlDTC3o7q5yyTG1pq27tgd
            9viAEE/JKTqAVI9EU19Ca9JZa5cMP3BmRbPh0fm1kVaeTxqnQDDB4sekUzrR9pcy
            n0Kl7i5cKBMKu2zAsh96/7IN+ZSKYB89zih0bmY+9Cpgadx6uTYCy4oy5YjWaWls
            f1ERxY18snbOV8X33+z7NhUIoPYI/IHw5NL1rrgCbWZJjwJ3ZoA4u9WWAPTH1ilW
            FapBeimEGxQAb/SOT0aZI3sJsKZqeewZNRYrsxPyU9/bKXyoXKtJVU7mLTrhcrfB
            ZCjYlK8rDBwifn/zpZgOrMQWHm+m7hQY6LGSyKe3R6Kw9i0WHc5I2C0ebUFBpMDS
            UQGXraxlPCiTYEd4w8xELoxQPW0iWlddtxSIn9R6D7F2eLHPmRQLLUk41x6WFnn9
            NXjzIj136bKhyJuxJFy6iRCj8QaMRqsJBsdG5A9ovTSG6w==
            =s2kC
            -----END PGP MESSAGE-----
        fp: 1F5DC61F0741F7CCF79A5A22C8182A589C9A04FB
    unencrypted_suffix: _unencrypted
    version: 3.3.1
