---
version: "2"

tasks:
  full-install-steps:
    cmds:
      - task: clean-generated-cf-values
      - task: build-cf
      - task: apply-cf

  clean-generated-cf-values:
    dir: ./deployments/cf-for-k8s/build
    cmds:
      - |
        ./build.sh clean-generated-cf-values

  build-cf:
    dir: ./deployments/cf-for-k8s/build
    cmds:
      - |
        ./build.sh build

  apply-cf:
    cmds:
      - |
        kapp deploy -a cf -f ./deployments/cf-for-k8s/_rendered/cf/cf-for-k8s-rendered.yml --yes

  delete-cf:
    cmds:
      - |
        kapp delete -a cf -y
