# https://cert-manager.io/docs/installation/kubernetes/#verifying-the-installation
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-test
  labels:
    istio-injection: disabled
---
apiVersion: cert-manager.io/v1beta1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: cert-manager-test
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  dnsNames:
    - example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
