# https://ruzickap.github.io/k8s-harbor/
# https://itnext.io/need-a-container-image-registry-and-helm-chart-repository-go-harbor-b0c0d4eafd3b
---
helmDefaults:
  kubeContext: kind-kind
  createNamespace: true
  recreatePods: false
  wait: true

repositories:
  - name: harbor
    url: https://helm.goharbor.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: harbor
    namespace: harbor
    chart: harbor/harbor
    version: ~1.3.x
    values:
      - config/harbor/values.yml

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: ~2.3.x
    values:
      - config/ingress-nginx/values.yml
