---
expose:
  type: clusterIP
  tls:
    enabled: true
    # Fill the name of secret if you want to use your own TLS certificate.
    # The secret contains keys named:
    # "tls.crt" - the certificate (required)
    # "tls.key" - the private key (required)
    # "ca.crt" - the certificate of CA (optional), this enables the download
    # link on portal to download the certificate of CA
    # These files will be generated automatically if the "secretName" is not set
    # secretName: "harbor-internal-tls-certs"
    secretName: "harbor-internal-tls-certs-ver-1"
    # commonName: harbor.harbor.svc.cluster.local
  clusterIP:
    name: harbor
    ports:
      httpPort: 80
      httpsPort: 443
      notaryPort: 4443

externalURL: https://harbor.harbor.svc.cluster.local

internalTLS:
  enabled: false

persistence:
  enabled: true
  resourcePolicy: ""
  persistentVolumeClaim:
    registry:
      storageClass: "standard"
      size: 5Gi
    chartmuseum:
      storageClass: "standard"
      size: 5Gi
    jobservice:
      storageClass: "standard"
      size: 1Gi
    database:
      storageClass: "standard"
      size: 1Gi
    redis:
      storageClass: "standard"
      size: 1Gi

logLevel: debug

harborAdminPassword: admin

nginx:
  podAnnotations: {}

portal:
  podAnnotations: {}

core:
  podAnnotations:
    sidecar.istio.io/rewriteAppHTTPProbers: "true"

jobservice:
  podAnnotations:
    sidecar.istio.io/rewriteAppHTTPProbers: "true"

registry:
  relativeurls: true
  podAnnotations: {}
  credentials:
    username: "harbor_registry_user"
    password: "harbor_registry_password"
    htpasswd: "harbor_registry_user:$2y$10$9L4Tc0DJbFFMB6RdSCunrOpTHdwhid4ktBJmLD00bYgqkkGOvll3m"

chartmuseum:
  enabled: false
  podAnnotations: {}

clair:
  enabled: false
  podAnnotations: {}

trivy:
  enabled: false
  podAnnotations: {}

notary:
  enabled: false
  podAnnotations: {}

database:
  type: internal
  podAnnotations:
    sidecar.istio.io/rewriteAppHTTPProbers: "true"

redis:
  type: internal
  podAnnotations: {}
