---
applications:
  - name: hash-browns
    memory: 256M
    no-route: true
    health-check-type: process
    docker:
      image: alexellis2/hashbrowns:1.2.0
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        # prometheus.io/port: 80 # results in Get "http://10.244.0.52:80/metrics": EOF
        prometheus.io/port: 8080 # success
        prometheus.io/path: /metrics
