apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-gershman
  region: us-east-2 # ohio

nodeGroups:
  - name: standard-workers
    instanceType: t3.small
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        externalDNS: true
