helmDefaults:
  kubeContext: gershman-admin@eks-gershman.us-east-2.eksctl.io
  # recreatePods: true

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

releases:

- name: concourse-web
  namespace: concourse-web
  chart: stable/concourse
  installed: false
  version: ~8.1.x
  values:
  - config/concourse-web/values.yml

- name: concourse-workers
  namespace: concourse-workers
  chart: stable/concourse
  installed: false
  version: ~8.1.x
  values:
  - config/concourse-workers/values.yml

- name: external-dns
  namespace: external-dns
  chart: stable/external-dns
  installed: true
  version: ~2.3.x
  values:
  - config/external-dns/values.yml

- name: nginx-ingress
  namespace: nginx-ingress
  chart: stable/nginx-ingress
  installed: true
  version: ~1.10.x
  values:
  - config/nginx-ingress/values.yml
