helmDefaults:
  kubeContext: docker-for-desktop
  # recreatePods: true

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: kubecost
  url: https://kubecost.github.io/cost-analyzer

releases:

- name: concourse-web
  namespace: concourse-web
  chart: stable/concourse
  installed: true
  version: ~8.1.x
  values:
  - config/concourse-web/values.yml

- name: concourse-workers
  namespace: concourse-workers
  chart: stable/concourse
  installed: true
  version: ~8.1.x
  values:
  - config/concourse-workers/values.yml

- name: kubecost
  namespace: kubecost
  chart: kubecost/cost-analyzer
  installed: true
  version: ~1.x.x
  values:
  - config/kubecost/values.yml
  secrets:
  - config/kubecost/secrets.yaml

- name: nginx-ingress
  namespace: nginx-ingress
  chart: stable/nginx-ingress
  installed: true
  version: ~1.10.x
  values:
  - config/nginx-ingress/values.yml
