---
version: "2"

tasks:
  default:
    cmds:
      - exit 1
      - |
        kubectl -n jaeger-operator get jaeger
        kubectl -n jaeger-operator delete jaeger.jaegertracing.io/jaeger-operator-jaeger
        kubectl -n jaeger-operator get pods -l app.kubernetes.io/instance=jaeger-operator-jaeger
        kubectl -n jaeger-operator logs -f -l app.kubernetes.io/instance=jaeger-operator-jaeger
      - |
        kubectl -n jaeger-operator get pods -l app.kubernetes.io/name=jaeger-operator
        kubectl -n jaeger-operator logs -f -l app.kubernetes.io/name=jaeger-operator
