#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Secret","metadata":{"name":"cf-system-cert"}})
#@overlay/remove
---
---
apiVersion: cert-manager.io/v1beta1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: aegershman+letsencrypt@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          route53:
            region: us-east-2

---
apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: cf-gershman-io-prod
  namespace: istio-system
spec:
  secretName: cf-system-cert
  dnsNames:
    - "*.cf.gershman.io"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Never
