---
jaeger:
  create: true
  spec:
    strategy: allInOne
    allInOne:
      options:
        log-level: debug
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: istio
      hosts:
        - jaeger.vcap.me
