---
postgresql:
  enabled: true

worker:
  enabled: false

web:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - concourse.vcap.me

concourse:
  web:
    clusterName: localhost
    externalUrl: http://concourse.vcap.me
    kubernetes:
      enabled: false
