# https://concourse-ci.org/tracing.html
# https://discuss.istio.io/t/help-with-production-jaeger-and-istio/4002
# https://medium.com/@masroor.hasan/tracing-infrastructure-with-jaeger-on-kubernetes-6800132a677
---
postgresql:
  enabled: true

worker:
  enabled: false

web:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/enable-opentracing: "true"
    hosts:
      - concourse.vcap.me

concourse:
  web:
    clusterName: localhost
    externalUrl: http://concourse.vcap.me
    kubernetes:
      enabled: false

    tracing:
      jaegerEndpoint: http://jaeger-operator-jaeger-collector-headless.jaeger-operator.svc.cluster.local:14268/api/traces
      jaegerTags: "iaas_type:kind,env:localhost"
      jaegerService: "concourse-web"

    prometheus:
      enabled: true
      ## If Prometheus operator is used, also create a servicemonitor object
      serviceMonitor:
        enabled: true
        interval: "30s"
