# https://github.com/cloudfoundry/cf-for-k8s/blob/master/deploy/kind/cluster.yml
# https://github.com/kubernetes-sigs/kind/blob/master/pkg/internal/apis/config/encoding/testdata/v1alpha4/valid-many-fields.yaml
# https://github.com/kubernetes-sigs/kind/pull/637
# https://kind.sigs.k8s.io/docs/user/ingress/
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.17.0
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
      - containerPort: 8443
        hostPort: 8443
