---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
  - path: cluster/build/concourse-web/_vendir
    contents:
      - path: manual
        manual: {}
      - path: upstream
        git:
          url: https://github.com/concourse/concourse-chart
          ref: 5d9c6e46e5bf81e67a02a8e7ac1e4b63dadcd485 # 13.0.0
        includePaths:
          - templates/**/*
          - .gitignore
          - Chart.yaml
          - README.md
          - values.yaml
  - path: cluster/build/concourse-workers/_vendir
    contents:
      - path: manual
        manual: {}
      - path: upstream
        git:
          url: https://github.com/concourse/concourse-chart
          ref: 5d9c6e46e5bf81e67a02a8e7ac1e4b63dadcd485 # 13.0.0
        includePaths:
          - templates/**/*
          - .gitignore
          - Chart.yaml
          - README.md
          - values.yaml
  - path: cluster/build/external-dns/_vendir
    contents:
      - path: manual
        manual: {}
      - path: upstream
        git:
          url: https://github.com/bitnami/charts
          ref: be5b30d4b65794d63d36449fc6e8a912bdccbdda # 3.3.0
        includePaths:
          - bitnami/external-dns/**/*
  - path: cluster/build/ingress-nginx/_vendir
    contents:
      - path: manual
        manual: {}
      - path: upstream
        git:
          url: https://github.com/kubernetes/ingress-nginx
          ref: 442f7bb71b5111206d8ed20d28746c35c7bd4b62 # 2.15.0
        includePaths:
          - charts/ingress-nginx/**/*
        excludePaths:
          - charts/ingress-nginx/ci/**/*

  - path: cluster/config/concourse-web/_ytt_lib
    contents:
      - path: concourse-web
        manual: {}
  - path: cluster/config/concourse-workers/_ytt_lib
    contents:
      - path: concourse-workers
        manual: {}
  - path: cluster/config/external-dns/_ytt_lib
    contents:
      - path: external-dns
        manual: {}
  - path: cluster/config/ingress-nginx/_ytt_lib
    contents:
      - path: ingress-nginx
        manual: {}
