---
apiVersion: v1
kind: Secret
metadata:
  name: basic-docker-user-pass
  annotations:
    build.pivotal.io/docker: harbor.vcap.me
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: Harbor12345
