---
apiVersion: v1
kind: Secret
metadata:
  name: basic-docker-user-pass
  annotations:
    # build.pivotal.io/docker: harbor.vcap.me
    # build.pivotal.io/docker: http://harbor-harbor-core.harbor.svc.cluster.local/v2/
    build.pivotal.io/docker: http://harbor-harbor-core.harbor.svc.cluster.local/
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: Harbor12345
