postgresql:
  enabled: true
  persistence:
    enabled: true
    size: 256M

worker:
  enabled: false

web:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - concourse.127.0.0.1.nip.io

concourse:
  web:
    clusterName: docker-for-desktop
    externalUrl: http://concourse.127.0.0.1.nip.io
    kubernetes:
      enabled: false
