---
version: "2"

includes:
  cf: ./deployments/cf-for-k8s/Taskfile.yml
  debug: ./Taskfile.debug.yml

tasks:
  cf-push:
    cmds:
      - |
        cf api --skip-ssl-validation https://api.vcap.me
        cf auth admin $(yq r ./deployments/cf-for-k8s/_rendered/cf/cf-values-generated.yml 'cf_admin_password')
        cf create-org test-org
        cf create-space -o test-org test-space
        cf target -o test-org -s test-space
      - | # push an app already built via docker:
        cf enable-feature-flag diego_docker
        cf push -f ./deployments/cf-for-k8s/config/user/cf-manifests/hash-browns-docker-no-routes.yml --strategy=rolling
        cf push -f ./deployments/cf-for-k8s/config/user/cf-manifests/hash-browns-docker-routes.yml --strategy=rolling
        cf push -f ./deployments/cf-for-k8s/config/user/cf-manifests/todo-ui-docker-routes.yml --strategy=rolling
      - | # push an app from source code:
        cf push test-node-app -p ./deployments/cf-for-k8s/build/_vendir/github.com/cloudfoundry/cf-for-k8s/tests/smoke/assets/test-node-app
        curl http://test-node-app.vcap.me/env
      - | # minibroker
        cf create-service-broker minibroker user pass http://minibroker-minibroker.minibroker.svc
        cf enable-service-access mysql
        cf enable-service-access redis
        cf enable-service-access mongodb
        cf enable-service-access mariadb
        cf create-service mariadb 10-3-22 mariadb-svc
        cf service mariadb-svc
        cf create-service-key mariadb-svc mykey
        cf bind-service todo-ui mariadb-svc
