---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
  - path: deployments/cf-for-k8s/build/_vendir
    contents:
      - path: github.com/cloudfoundry/cf-for-k8s
        git:
          url: https://github.com/cloudfoundry/cf-for-k8s
          ref: 56db8a14723cae48ea2e995929954aeeb49cdd6c # beyond v0.4.0
        includePaths:
          - config-optional/**/*
          - config/**/*
          - hack/generate-values.sh
          - tests/smoke/assets/test-node-app/**/*
      - path: github.com/cloudfoundry/cf-k8s-networking
        git:
          url: https://github.com/cloudfoundry/cf-k8s-networking
          ref: bc73158c3b446b72e4f5b9365cee58b4383d835e
        includePaths:
          - config/*
          - config/crd/**/*
          - config/istio-config/**/*
          - config/istio/generated/**/*
          - config/routecontroller/**/*
  - path: deployments/minibroker/build/_vendir
    contents:
      - path: github.com/kubernetes-sigs/minibroker
        git:
          url: https://github.com/kubernetes-sigs/minibroker
          ref: e04f5d07aa58a0af06cd87b26a5f90842d3b9e0a
          disableAutoChecksumValidation: true
        includePaths:
          - charts/minibroker/**/*
  - path: deployments/prometheus-operator/build/_vendir
    contents:
      - path: github.com/helm/charts/prometheus-operator
        git:
          url: https://github.com/helm/charts
          ref: fbf8233ea49d5ac62b1f0323012badff13246efe # 9.0.1
          disableAutoChecksumValidation: true
        includePaths:
          - stable/prometheus-operator/**/*
  - path: deployments/service-catalog/build/_vendir
    contents:
      - path: github.com/kubernetes-sigs/service-catalog
        git:
          url: https://github.com/kubernetes-sigs/service-catalog
          ref: f7c033da6649968820d17bc8cf35e7fd7b9623bb
          disableAutoChecksumValidation: true
        includePaths:
          - charts/catalog/**/*
          - charts/healthcheck/**/*
          - charts/ups-broker/**/*
