---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
  - path: deployments/cf-for-k8s/build/_vendir
    contents:
      - path: github.com/cloudfoundry/cf-for-k8s
        git:
          url: https://github.com/cloudfoundry/cf-for-k8s
          ref: a339593d222cec1481a4e2a35be4e6bab0be881a # beyond v0.4.0
        includePaths:
          - config-optional/**/*
          - config/**/*
          - hack/generate-values.sh
          - tests/smoke/assets/test-node-app/**/*
      - path: github.com/cloudfoundry/cf-k8s-networking
        git:
          url: https://github.com/cloudfoundry/cf-k8s-networking
          ref: 994575c1331b64f4e8d0a63edd3b2329258d6f00
        includePaths:
          - config/*
          - config/crd/**/*
          - config/istio-config/**/*
          - config/istio/generated/**/*
          - config/routecontroller/**/*
  - path: deployments/minibroker/build/_vendir
    contents:
      - path: github.com/kubernetes-sigs/minibroker
        git:
          url: https://github.com/kubernetes-sigs/minibroker
          ref: e04f5d07aa58a0af06cd87b26a5f90842d3b9e0a
          disableAutoChecksumValidation: true
        includePaths:
          - charts/minibroker/**/*
  - path: deployments/prometheus-operator/build/_vendir
    contents:
      - path: github.com/helm/charts/prometheus-operator
        git:
          url: https://github.com/helm/charts
          ref: f191697fdec967f2df92e41514a56535927e40b0 # 8.16.1
          disableAutoChecksumValidation: true
        includePaths:
          - stable/prometheus-operator/**/*
  - path: deployments/service-catalog/build/_vendir
    contents:
      - path: github.com/kubernetes-sigs/service-catalog
        git:
          url: https://github.com/kubernetes-sigs/service-catalog
          ref: 18c0d73e1fbc16542276c314689a20bc81a98221
          disableAutoChecksumValidation: true
        includePaths:
          - charts/catalog/**/*
          - charts/healthcheck/**/*
          - charts/ups-broker/**/*
