---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
  - path: deployments/cf-for-k8s/build/_vendir
    contents:
      - path: github.com/cloudfoundry/cf-for-k8s
        git:
          url: https://github.com/cloudfoundry/cf-for-k8s
          ref: ee805a629c4a33fb347db07526a0ca0ec3737ae7 # beyond v0.4.0
        includePaths:
          - config-optional/**/*
          - config/**/*
          - hack/generate-values.sh
          - tests/smoke/assets/test-node-app/**/*
      - path: github.com/cloudfoundry/cf-k8s-networking
        git:
          url: https://github.com/cloudfoundry/cf-k8s-networking
          ref: 366d671101a846b7c6cfd1d1b2cd18ffd750ecb1
        includePaths:
          - config/*
          - config/crd/**/*
          - config/istio-config/**/*
          - config/istio/generated/**/*
          - config/routecontroller/**/*
  - path: deployments/minibroker/build/_vendir
    contents:
      - path: github.com/kubernetes-sigs/minibroker
        git:
          url: https://github.com/kubernetes-sigs/minibroker
          ref: 35de1ab212e2698abeb8451660fea8d1f938eb12
          disableAutoChecksumValidation: true
        includePaths:
          - charts/minibroker/**/*
  - path: deployments/prometheus-operator/build/_vendir
    contents:
      - path: github.com/helm/charts/prometheus-operator
        git:
          url: https://github.com/helm/charts
          ref: 0a7733450100af14cd8705c611b9a1ac048e5000 # 8.15.11
          disableAutoChecksumValidation: true
        includePaths:
          - stable/prometheus-operator/**/*
  - path: deployments/service-catalog/build/_vendir
    contents:
      - path: github.com/kubernetes-sigs/service-catalog
        git:
          url: https://github.com/kubernetes-sigs/service-catalog
          ref: 5068f67d9616bab9e21dae8a161578a034a0803a
          disableAutoChecksumValidation: true
        includePaths:
          - charts/catalog/**/*
          - charts/healthcheck/**/*
          - charts/ups-broker/**/*
