---
apiVersion: v1
kind: Secret
metadata:
  name: basic-docker-user-pass
  annotations:
    build.pivotal.io/docker: core-harbor.127.0.0.1.xip.io
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: Harbor12345
