# https://github.com/pivotal/kpack/blob/master/docs/secrets.md
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-git-user-pass
  annotations:
    build.pivotal.io/git: https://github.com/aegershman/kpack-registry-test
type: kubernetes.io/basic-auth
stringData:
  username: aegershman
  password: axyz # TODO cycle and remove
