---
helmDefaults:
  kubeContext: kind-kind

repositories:
  - name: minibroker
    url: https://minibroker.blob.core.windows.net/charts
  - name: svc-cat
    url: https://svc-catalog-charts.storage.googleapis.com

releases:
  - name: minibroker
    namespace: minibroker
    createNamespace: true
    chart: minibroker/minibroker
    installed: true
    wait: true
    version: ~0.x.x
    values:
      - config/minibroker/values.yml

  - name: service-catalog
    namespace: catalog
    createNamespace: true
    chart: svc-cat/catalog
    installed: false
    wait: true
    version: ~0.x.x
    values:
      - config/service-catalog/values.yml
