---
helmDefaults:
  kubeContext: kind-kind
  createNamespace: true
  recreatePods: false
  wait: true

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: minibroker
    url: https://minibroker.blob.core.windows.net/charts
  - name: svc-cat
    url: https://svc-catalog-charts.storage.googleapis.com

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    installed: true
    version: ~2.7.x
    values:
      - config/ingress-nginx/values.yml

  - name: minibroker
    namespace: minibroker
    chart: minibroker/minibroker
    installed: true
    version: ~0.x.x
    values:
      - config/minibroker/values.yml

  - name: service-catalog
    namespace: catalog
    chart: svc-cat/catalog
    installed: false
    version: ~0.x.x
    values:
      - config/service-catalog/values.yml
