---
helmDefaults:
  kubeContext: kind-kind
  createNamespace: true
  recreatePods: false
  wait: false

repositories:
  - name: harbor
    url: https://helm.goharbor.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts
  - name: minibroker
    url: https://minibroker.blob.core.windows.net/charts
  - name: svc-cat
    url: https://svc-catalog-charts.storage.googleapis.com

releases:
  - name: harbor
    namespace: harbor
    chart: harbor/harbor
    installed: true
    version: ~1.3.x
    values:
      - config/harbor/values.yml

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    installed: false
    version: ~2.9.x
    needs:
      - prometheus-operator/prometheus-operator
    values:
      - config/ingress-nginx/values.yml

  - name: jaeger-operator
    namespace: jaeger-operator
    chart: jaegertracing/jaeger-operator
    installed: true
    version: ~2.15.x
    values:
      - config/jaeger-operator/values.yml

  - name: minibroker
    namespace: minibroker
    # chart: minibroker/minibroker
    chart: config/minibroker/vendor/github.com/kubernetes-sigs/minibroker/charts/minibroker
    installed: false
    version: ~0.x.x
    values:
      - config/minibroker/values/values.yml

  - name: prometheus-operator
    namespace: prometheus-operator
    chart: stable/prometheus-operator
    installed: true
    version: ~8.15.x
    values:
      - config/prometheus-operator/values.yml

  - name: service-catalog
    namespace: catalog
    # chart: svc-cat/catalog
    chart: config/service-catalog/vendor/github.com/kubernetes-sigs/service-catalog/charts/catalog
    installed: false
    version: ~0.x.x
    needs:
      - minibroker/minibroker
    values:
      - config/service-catalog/values/values.yml
