---
version: "2"

includes:
  debug: ./Taskfile.debug.yml

tasks:
  full-install-steps:
    cmds:
      - task: clean-generated-values
      - task: generate-values
      - task: apply-cf

  clean-generated-values:
    cmds:
      - | # when you remove these from /tmp and re-run the generate-values script it'll give you new passwords, certs, etc.
        rm -f /tmp/cf-values.yml
        rm -f /tmp/cf-for-k8s-rendered.yml
        rm -rf /tmp/vcap.me

  generate-values:
    cmds:
      - | # vcap.me == nip.io == xip.io, allowing for localhost dns
        ./config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/hack/generate-values.sh \
          --silence-hack-warning \
          --cf-domain vcap.me \
          >rendered/cf/cf-values-generated.yml
      - |
        ytt \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/remove-ingressgateway-service.yml \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/remove-resource-requirements.yml \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/add-metrics-server-components.yml \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/patch-metrics-server.yml \
          -f rendered/cf/cf-values-generated.yml \
          -f config/cf/user/opsfiles/cf-registry-values.yml \
          -f config/harbor/user/opsfiles/harbor-namespace.yml \
          -f config/harbor/user/opsfiles/harbor-virtual-service.yml \
          -f config/jaeger-operator/user/opsfiles/jaeger-operator-namespace.yml \
          -f config/jaeger-operator/user/opsfiles/jaeger-virtual-service.yml \
          -f config/prometheus-operator/user/opsfiles/alertmanager-virtual-service.yml \
          -f config/prometheus-operator/user/opsfiles/grafana-virtual-service.yml \
          -f config/prometheus-operator/user/opsfiles/prometheus-operator-namespace.yml \
          -f config/prometheus-operator/user/opsfiles/prometheus-virtual-service.yml \
          >rendered/cf/cf-for-k8s-rendered.yml

  apply-cf:
    cmds:
      - |
        kapp deploy -a cf -f rendered/cf/cf-for-k8s-rendered.yml --yes

  delete-cf:
    cmds:
      - |
        kapp delete -a cf -y
