---
version: "2"

includes:
  debug: ./Taskfile.debug.yml

tasks:
  full-install-steps:
    cmds:
      - task: clean-generated-values
      - task: generate-values
      - task: apply-cf

  clean-generated-values:
    cmds:
      - | # when you remove these from /tmp and re-run the generate-values script it'll give you new passwords, certs, etc.
        rm -f /tmp/cf-values.yml
        rm -f /tmp/cf-for-k8s-rendered.yml
        rm -rf /tmp/vcap.me

  generate-values:
    cmds:
      - | # vcap.me == nip.io == xip.io, allowing for localhost dns
        ./config/cf/user/generate/generate-values.sh \
          --silence-hack-warning \
          --cf-domain vcap.me \
          >rendered/cf/cf-values-generated.yml
      - |
        ytt \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/remove-ingressgateway-service.yml \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/remove-resource-requirements.yml \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/add-metrics-server-components.yml \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/patch-metrics-server.yml \
          -f rendered/cf/cf-values-generated.yml \
          -f config/cf/user/opsfiles/cf-registry-values.yml \
          -f config/harbor/user/opsfiles/harbor-namespace.yml \
          -f config/harbor/user/opsfiles/harbor-virtual-service.yml \
          -f config/jaeger-operator/user/opsfiles/jaeger-operator-namespace.yml \
          -f config/jaeger-operator/user/opsfiles/jaeger-virtual-service.yml \
          -f config/minibroker/user/opsfiles/minibroker-namespace.yml \
          -f config/prometheus-operator/user/opsfiles/alertmanager-virtual-service.yml \
          -f config/prometheus-operator/user/opsfiles/grafana-virtual-service.yml \
          -f config/prometheus-operator/user/opsfiles/prometheus-operator-namespace.yml \
          -f config/prometheus-operator/user/opsfiles/prometheus-virtual-service.yml \
          -f config/service-catalog/user/opsfiles/catalog-namespace.yml \
          >rendered/cf/cf-for-k8s-rendered.yml

  apply-cf:
    cmds:
      - |
        kapp deploy -a cf -f rendered/cf/cf-for-k8s-rendered.yml --yes

  delete-cf:
    cmds:
      - |
        kapp delete -a cf -y

  cf-push:
    cmds:
      - |
        cf api --skip-ssl-validation https://api.vcap.me
        cf auth admin $(yq r rendered/cf/cf-values-generated.yml 'cf_admin_password')
        cf create-org test-org
        cf create-space -o test-org test-space
        cf target -o test-org -s test-space
      - | # push an app already built via docker:
        cf enable-feature-flag diego_docker
        cf push -f config/cf/user/cf-manifests/hash-browns-docker-no-routes.yml --strategy=rolling
        cf push -f config/cf/user/cf-manifests/hash-browns-docker-routes.yml --strategy=rolling
        cf push -f config/cf/user/cf-manifests/todo-ui-docker-routes.yml --strategy=rolling
      - | # push an app from source code:
        cf push test-node-app -p config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/tests/smoke/assets/test-node-app
        curl http://test-node-app.vcap.me/env
      - | # minibroker
        cf create-service-broker minibroker user pass http://minibroker-minibroker.minibroker.svc
        cf enable-service-access mysql
        cf enable-service-access redis
        cf enable-service-access mongodb
        cf enable-service-access mariadb
        cf create-service mariadb 10-3-22 mariadb-svc
        cf service mariadb-svc
        cf create-service-key mariadb-svc mykey
        cf bind-service todo-ui mariadb-svc
