# https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/deploy-local.md
# https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/deploy.md
# https://github.com/cloudfoundry/cf-k8s-networking/blob/917b615a745510ec944ab8f66efdd1fa78c5fc6b/doc/managing-certificates-for-application-ingress.md
# https://github.com/cloudfoundry/cf-k8s-networking/tree/master/doc/no-loadbalancer
---
version: "2"

tasks:
  full-install-steps:
    cmds:
      - task: clean-generated-values
      - task: generate-values
      - task: apply-cf
      # - task: post-install

  clean-generated-values:
    cmds:
      - | # when you remove these from /tmp and re-run the generate-values script it'll give you new passwords, certs, etc.
        rm -f /tmp/cf-values.yml
        rm -f /tmp/cf-for-k8s-rendered.yml
        rm -rf /tmp/vcap.me

  generate-values:
    cmds:
      - | # vcap.me == nip.io == xip.io, allowing for localhost dns
        ./config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/hack/generate-values.sh \
          --silence-hack-warning \
          --cf-domain vcap.me \
          >config/cf/values/cf-values.yml
      - | # assumes harbor is deployed and ready to roll
        ytt \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/remove-ingressgateway-service.yml \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/remove-resource-requirements.yml \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/add-metrics-server-components.yml \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/patch-metrics-server.yml \
          -f config/cf/values/cf-values.yml \
          -f config/cf/values/config-optional/cf-registry-values.yml \
          -f config/cf/values/config-optional/cf-system-cert-extra-hosts.yml \
          >config/cf/values/cf-for-k8s-rendered.yml

  apply-cf:
    cmds:
      - |
        kapp deploy -a cf -f config/cf/values/cf-for-k8s-rendered.yml --yes

  delete-cf:
    cmds:
      - |
        kapp delete -a cf -y

  post-install:
    cmds:
      - |
        cf api --skip-ssl-validation https://api.vcap.me
        cf auth admin $(yq r config/cf/values/cf-values.yml 'cf_admin_password')
        cf create-org test-org
        cf create-space -o test-org test-space
        cf target -o test-org -s test-space
      - | # push an app already built via docker:
        cf enable-feature-flag diego_docker
        cf push -f config/cf/values/example-docker-cf-manifest-hash-browns.yml
        cf push -f config/cf/values/example-docker-cf-manifest-hash-browns-no-web.yml
        cf push -f config/cf/values/example-docker-cf-manifest-todo-ui.yml
      - | # push an app from source code:
        cf push test-node-app -p config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/tests/smoke/assets/test-node-app
        curl http://test-node-app.vcap.me/env
      - | # assuming minibroker is installed:
        cf create-service-broker minibroker user pass http://minibroker-minibroker.minibroker.svc
        cf enable-service-access mysql
        cf enable-service-access redis
        cf enable-service-access mongodb
        cf enable-service-access mariadb
        cf create-service mariadb 10-3-22 mariadb-svc
        cf service mariadb-svc
        cf create-service-key mariadb-svc mykey
        cf bind-service todo-ui mariadb-svc
      - | # debugging
        kubectl -n cf-system logs -f -lapp=log-cache --all-containers --max-log-requests=6
        kubectl -n cf-system get pods
        kubectl -n cf-system logs -f eirini-754669b789-z4jw5 -c istio-proxy
        kubectl -n cf-system logs -f eirini-754669b789-z4jw5 -c opi
        kubectl -n cf-system logs -f cf-api-kpack-watcher-77f9967c4b-mwltr -c cf-api-kpack-watcher
        kubectl -n cf-system logs -f cf-api-server-64dbfb9d-dtcsh -c cf-api-server --tail 250
        kubectl -n cf-system logs -f cf-api-worker-6c9dd76fcd-gr9h4 -c cf-api-worker
        kubectl -n cf-system logs -f routecontroller-78d58969bb-4r4mf -c routecontroller
        kubectl -n cf-workloads-staging get pods
        kubectl -n cf-workloads-staging get images -o yaml
        kubectl -n cf-workloads-staging describe images
        kubectl -n cf-workloads-staging describe builds
        kubectl -n cf-system get cm
        kubectl -n cf-system get cm eirini-ver-1 -o yaml
        kubectl -n cf-system get cm cloud-controller-ng-yaml-ver-1  -o yaml
        kubectl -n cf-system get cm nginx-ver-1  -o yaml
        kubectl -n cf-system get cm routecontroller-config-ver-1  -o yaml
        kubectl -n cf-workloads-staging get secrets
        kubectl -n cf-workloads-staging get secret cc-kpack-registry-auth-secret-ver-1 -o yaml

  harbor:
    cmds:
      - exit 1
      # for dockerhub, the registry auth target is "https://index.docker.io/v1/".
      # notice "library" is the project and "kuard-amd64" is the repository;
      # the repository was created automatically by virtue of the push.
      - |
        kubectl -n cf-workloads-staging get images
        logs -namespace cf-workloads-staging -image IMAGEHERE
      - |
        kubectl -n harbor port-forward svc/harbor 8080:80
        kubectl -n cf-workloads-staging describe pods
        curl -u admin:admin localhost:8080/api/v2.0/systeminfo
        curl localhost:8080/api/v2.0/systeminfo
        curl localhost:8080/api/v2.0/users/current
        curl -u admin:admin localhost:8080/api/v2.0/users/current
        curl -u admin:admin localhost:8080/api/v2.0/projects
        curl -u admin:admin localhost:8080/api/v2.0/projects/library/repositories
      - |
        kubectl -n harbor port-forward svc/harbor 8080:80
        kubectl -n harbor port-forward service/harbor-harbor-core 4107:80
        kubectl -n harbor port-forward deployment/harbor-harbor-core 4107:8080
      - |
        kubectl -n harbor logs -f -lapp=harbor -lcomponent=core --tail 250
        kubectl -n harbor logs -f -lapp=harbor -lcomponent=database --tail 250
        kubectl -n harbor logs -f -lapp=harbor -lcomponent=jobservice --tail 250
        kubectl -n harbor logs -f -lapp=harbor -lcomponent=nginx
        kubectl -n harbor logs -f -lapp=harbor -lcomponent=portal --tail 250
        kubectl -n harbor logs -f -lapp=harbor -lcomponent=redis --tail 250
        kubectl -n harbor logs -f -lapp=harbor -lcomponent=registry -c registry
      - |
        docker login --username admin --password Harbor12345 localhost:4107
        docker pull gcr.io/kuar-demo/kuard-amd64:blue
        docker tag gcr.io/kuar-demo/kuard-amd64:blue localhost:4107/library/kuard-amd64:blue
        docker images
        docker push localhost:4107/library/kuard-amd64:blue

  prometheus-operator:
    cmds:
      - exit 1
      - |
        kubectl apply -f config/cf/values/cf-hash-browns-service-monitor.yaml
        cf push -f config/cf/values/example-docker-cf-manifest-hash-browns.yml
        cf push -f config/cf/values/example-docker-cf-manifest-hash-browns-no-web.yml
      - |
        kubectl delete -f config/cf/values/cf-hash-browns-service-monitor.yaml
        kubectl -n cf-workloads get servicemonitor -o yaml
        kubectl -n cf-workloads get endpoints -o yaml
        kubectl -n ingress-nginx get servicemonitor -o yaml
        kubectl -n prometheus-operator logs -f -lapp=prometheus-operator-operator --all-containers=true

  svccat:
    cmds:
      - | # not intended to be ran as a task, just for holding command strings
        exit 1
      - | # minibroker
        svcat register minibroker --url http://minibroker-minibroker.minibroker.svc --scope cluster
        svcat get brokers
        svcat sync broker minibroker
        svcat marketplace
        svcat provision redis-test --class redis --plan 5-0-7
        svcat provision redis-test --class redis --plan 5-0-7 --param p1=foo --param p2=bar --secret 'creds[db]'
        svcat bind redis-test --name redis-test
        svcat describe instance redis-test
        svcat deprovision redis-test
        svcat get instances

      - | # https://svc-cat.io/docs/cli/
        svcat register ups-broker --url http://ups-broker-ups-broker.ups-broker.svc.cluster.local --scope cluster
        svcat get brokers
        svcat sync broker ups-broker
        svcat marketplace
        svcat provision ups-instance --class user-provided-service --plan default
        svcat get instances
        svcat bind ups-instance --name ups-binding
        svcat bind ups-instance
        svcat describe instance ups-instance
        svcat unbind ups-instance
        svcat unbind --name ups-binding
        svcat deregister ups-broker --scope cluster
        svcat get brokers --scope namespace

      - | # https://svc-cat.io/docs/walkthrough/
        svcat get classes
        kubectl get clusterserviceclasses
        svcat describe class mariadb
        kubectl get clusterserviceclasses mariadb -o yaml
        svcat get plans
        kubectl get clusterserviceplans
        svcat describe plan 10-3-22 --scope cluster
        kubectl get clusterserviceplans mariadb-10-3-22 -o yaml
        svcat deprovision -n test-ns mini-instance
        kubectl delete clusterservicebrokers minibroker

  istio:
    cmds:
      - exit 1
      - | # https://istio.io/latest/docs/ops/common-problems/injection/
        kubectl get mutatingwebhookconfiguration istio-sidecar-injector -o yaml | grep "namespaceSelector:" -A5
        kubectl get namespace -L istio-injection
      - | # setup prometheus namespace with istio annotation injection label
        kubectl label --overwrite namespace prometheus-operator "istio-injection=enabled"
      - | # example of using a virtualservice for ingress against non-CF deployments
        kubectl apply -f config/harbor/harbor-virtual-service.yml
        kubectl apply -f config/jaeger-operator/jaeger-virtual-service.yml
        kubectl apply -f config/prometheus-operator/alertmanager-virtual-service.yml
        kubectl apply -f config/prometheus-operator/grafana-virtual-service.yml
        kubectl apply -f config/prometheus-operator/prometheus-virtual-service.yml
      - |
        kubectl delete -f config/harbor/harbor-virtual-service.yml
        kubectl delete -f config/jaeger-operator/jaeger-virtual-service.yml
        kubectl delete -f config/prometheus-operator/alertmanager-virtual-service.yml
        kubectl delete -f config/prometheus-operator/grafana-virtual-service.yml
        kubectl delete -f config/prometheus-operator/prometheus-virtual-service.yml
