---
version: "2"

# https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/deploy-local.md
# https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/deploy.md
tasks:
  apply-metrics-server:
    cmds: # we're using metrics-server packaged with cf-for-k8s, but will leave this here
      - kubectl apply --recursive --filename config/cf/vendor/github.com/kubernetes-sigs

  generate-values:
    cmds:
      - | # vcap.me == nip.io == xip.io, allowing for localhost dns
        ./config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/hack/generate-values.sh \
          --cf-domain vcap.me \
          >config/cf/values/cf-values.yml
      - |
        ytt \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/remove-ingressgateway-service.yml \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/remove-resource-requirements.yml \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/add-metrics-server-components.yml \
          -f config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/patch-metrics-server.yml \
          -f config/cf/values/cf-values.yml \
          >config/cf/values/cf-for-k8s-ytt.yml

  clean-generated-values:
    cmds:
      - | # when you remove these from /tmp and re-run the generate-values script it'll give you new passwords, certs, etc.
        rm -f /tmp/cf-values.yml
        rm -f /tmp/cf-for-k8s-ytt.yml
        rm -rf /tmp/vcap.me

  apply-cf:
    cmds:
      - kapp deploy -a cf -f config/cf/values/cf-for-k8s-ytt.yml --yes

  delete-cf:
    cmds:
      - kapp delete -a cf -y

  post-install:
    cmds:
      - |
        cf api --skip-ssl-validation https://api.vcap.me
        cf auth admin $(yq r config/cf/values/cf-values.yml 'cf_admin_password')
      - |
        cf create-org test-org
        cf create-space -o test-org test-space
        cf target -o test-org -s test-space
      - | # push an app already built via docker:
        cf enable-feature-flag diego_docker
        cf push -f config/cf/values/example-docker-cf-manifest-hash-browns.yml
        cf push -f config/cf/values/example-docker-cf-manifest-todo-ui.yml
      - | # push an app from source code:
        cf push test-node-app -p config/cf/vendor/github.com/cloudfoundry/cf-for-k8s/tests/smoke/assets/test-node-app
        curl http://test-node-app.vcap.me/env
      - | # assuming minibroker is installed:
        cf create-service-broker minibroker user pass http://minibroker-minibroker.minibroker.svc.cluster.local
        cf enable-service-access mysql
        cf enable-service-access redis
        cf enable-service-access mongodb
        cf enable-service-access mariadb
        cf create-service mariadb 10-3-22 mariadb-svc
        cf service mariadb-svc
        cf create-service-key mariadb-svc mykey
        cf bind-service todo-ui mariadb-svc

  full-install-steps:
    cmds:
      # - task: apply-metrics-server
      # - task: clean-generated-values
      - task: generate-values
      - task: apply-cf
      # - task: post-install

  debug:
    cmds:
      - | # not intended to be ran as a task, just for holding command strings
        exit 1
        kubectl -n cf-system logs -f -lapp=log-cache --all-containers --max-log-requests=6

  svccat:
    cmds: # https://svc-cat.io/docs/walkthrough/
      - exit 1
      - | # not intended to be ran as a task, just for holding command strings
        svcat get classes
        kubectl get clusterserviceclasses
        svcat describe class mariadb
        kubectl get clusterserviceclasses mariadb -o yaml
        svcat get plans
        kubectl get clusterserviceplans
        svcat describe plan 10-3-22 --scope cluster
        kubectl get clusterserviceplans mariadb-10-3-22 -o yaml
        svcat deprovision -n test-ns mini-instance
        kubectl delete clusterservicebrokers minibroker
