# https://github.com/k14s/vendir/blob/master/docs/vendir-spec.md
# https://github.com/k14s/vendir/blob/master/examples/git-and-manual/vendir.yml
---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: config/cf
    contents:
      - path: vendor/github.com/kubernetes-sigs/metrics-server
        githubRelease:
          slug: kubernetes-sigs/metrics-server
          tag: v0.3.6
          disableAutoChecksumValidation: true
        includePaths:
          - components.yaml
      - path: vendor/github.com/cloudfoundry/cf-for-k8s
        git:
          url: https://github.com/cloudfoundry/cf-for-k8s
          ref: 6b94aa1dcfe27c432bc72fd0389fef860a73c4d5 # beyond v0.3.0
        includePaths:
          - bin/**/*
          - config-optional/**/*
          - config/**/*
          - deploy/kind/**/*
          - hack/**/*
          - tests/smoke/assets/test-node-app/**/*
      - path: values
        manual: {}
  - path: config/harbor
    contents:
      - path: vendor/github.com/goharbor/harbor-helm
        git:
          url: https://github.com/goharbor/harbor-helm
          ref: 83428a9e39074a0498960cbfb961473748f73de3
          disableAutoChecksumValidation: true
        includePaths:
          - cert/**/*
          - conf/**/*
          - templates/**/*
          - .gitignore
          - .helmignore
          - Chart.yaml
          - values.yaml
      - path: values
        manual: {}
  - path: config/minibroker
    contents:
      - path: vendor/github.com/kubernetes-sigs/minibroker
        git:
          url: https://github.com/kubernetes-sigs/minibroker
          ref: e50e4bc41f03ae2e10daaf9522f2aafb32bc7ea3
          disableAutoChecksumValidation: true
        includePaths:
          - charts/minibroker/**/*
      - path: values
        manual: {}
  - path: config/service-catalog
    contents:
      - path: vendor/github.com/kubernetes-sigs/service-catalog
        git:
          url: https://github.com/kubernetes-sigs/service-catalog
          ref: 5068f67d9616bab9e21dae8a161578a034a0803a
          disableAutoChecksumValidation: true
        includePaths:
          - charts/catalog/**/*
          - charts/healthcheck/**/*
          - charts/ups-broker/**/*
      - path: values
        manual: {}
