---
version: "2"

tasks:
  login:
    cmds:
      - fly -t localhost login -c http://concourse.vcap.me -u test -p test -n main -k
      - fly -t localhost sync

  set:
    cmds:
      - fly -t localhost sp -p demo -c demo/pipeline.yml -l demo/params.yml -n
