---
helmDefaults:
  cleanupOnFail: false
  createNamespace: true
  force: false
  historyMax: 2
  kubeContext: kind-kind
  wait: true

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: quarks
    url: https://cloudfoundry-incubator.github.io/quarks-helm
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: stratos
    url: https://cloudfoundry.github.io/stratos

releases:
  - name: cf-operator
    namespace: cf-operator
    chart: quarks/cf-operator
    version: 5.0.0
    installed: true
    needs:
      - ingress-nginx/ingress-nginx
    values:
      - deployments/cf-operator/values.yml

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    installed: true
    version: ~2.11.x
    values:
      - deployments/ingress-nginx/values.yml

  - name: kubecf
    namespace: kubecf
    createNamespace: false
    chart: https://github.com/cloudfoundry-incubator/kubecf/releases/download/v2.3.0/kubecf-v2.3.0.tgz
    installed: true
    wait: false
    needs:
      - cf-operator/cf-operator
      - ingress-nginx/ingress-nginx
    values:
      - deployments/kubecf/values.yml

  - name: stratos
    namespace: stratos
    chart: stratos/console
    installed: false
    version: ~3.2.x
    needs:
      - ingress-nginx/ingress-nginx
      - kubecf/kubecf
    values:
      - deployments/stratos/values.yml
