---
version: "2"

tasks:
  get-kind-node-ip:
    cmds:
      - |
        kubectl get node kind-control-plane --output jsonpath='{ .status.addresses[?(@.type == "InternalIP")].address }'

  logs-placeholder:
    cmds: # not to be actually ran as a task; just here for copy-paste-ability
      - exit 1
      - |
        kubectl logs -f --tail=250 deployment.apps/cf-operator
        kubectl logs -f --tail=250 deployment.apps/cf-operator-quarks-job
      - |
        kubectl -n kubecf get all
        kubectl -n kubecf get pods
        kubectl -n kubecf get sts
      - | # trust me, it's kind of a fun game to follow this tree of thing-waiting-on-thing
        kubectl -n kubecf logs -f sts/adapter -c wait-for
        kubectl -n kubecf logs -f sts/api -c wait-for
        kubectl -n kubecf logs -f sts/bits -c wait-for
        kubectl -n kubecf logs -f sts/credhub -c wait-for
        kubectl -n kubecf logs -f sts/diego-api -c wait-for
        kubectl -n kubecf logs -f sts/doppler -c wait-for
        kubectl -n kubecf logs -f sts/eirini -c wait-for
        kubectl -n kubecf logs -f sts/log-api -c wait-for
        kubectl -n kubecf logs -f sts/nats -c wait-for
        kubectl -n kubecf logs -f sts/router -c wait-for
        kubectl -n kubecf logs -f sts/routing-api -c wait-for
        kubectl -n kubecf logs -f sts/singleton-blobstore -c wait-for
        kubectl -n kubecf logs -f sts/uaa -c wait-for
      - |
        kubectl -n kubecf logs -f --tail=250 database-0 -c database
        kubectl -n kubecf logs -f --tail=250 database-0 -c logs
      - |
        kubectl -n kubecf describe pod -lquarks.cloudfoundry.org/qjob-name=ig-kubecf
        kubectl -n kubecf logs -f -lquarks.cloudfoundry.org/qjob-name=ig-kubecf
      - |
        kubectl -n eirini get pods
        kubectl -n ingress-nginx logs -f --tail 250 -lapp.kubernetes.io/name=ingress-nginx
        kubectl -n kubecf logs -f --tail 250 -lname=bits
        kubectl -n kubecf logs -f --tail 250 api-0 --all-containers --max-log-requests=60
        kubectl -n kubecf logs -f --tail 250 api-0 -c cloud-controller-ng-cloud-controller-ng
        kubectl -n kubecf logs -f --tail 250 api-0 -c route-registrar-route-registrar
        kubectl -n kubecf logs -f api-0

  uaa-zone-debug:
    cmds:
      - exit 1
      - |
        uaa target uaa.kubecf.vcap.me --skip-ssl-validation
        uaa get-password-token cf -s "" -u admin -p "$(kubectl -n kubecf get secret var-cf-admin-password -o jsonpath='{.data.password}' | base64 --decode)"
        uaa userinfo -v

  post-install:
    cmds:
      - |
        cf api --skip-ssl-validation api.kubecf.vcap.me
        cf auth admin $(kubectl -n kubecf get secret var-cf-admin-password -o jsonpath='{.data.password}' | base64 --decode)
        cf create-org scratch-org
        cf create-space scratch-space -o scratch-org
        cf target -o scratch-org -s scratch-space
        cf enable-feature-flag diego_docker
        cf push -f deployments/kubecf/cf-manifests/hash-browns-docker-no-routes.yml
        cf push -f deployments/kubecf/cf-manifests/hash-browns-docker-routes.yml
        cf push -f deployments/kubecf/cf-manifests/todo-ui-docker-routes.yml
