---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
  - path: cluster/build/cf-operator/_vendir
    contents:
      - path: manual
        manual: {}
      - path: upstream
        githubRelease:
          slug: cloudfoundry-incubator/quarks-operator
          tag: v6.1.15
          disableAutoChecksumValidation: true
          unpackArchive:
            path: cf-operator-6.1.15+0.g89a56300.tgz
  - path: cluster/build/ingress-nginx/_vendir
    contents:
      - path: manual
        manual: {}
      - path: upstream
        git:
          url: https://github.com/kubernetes/ingress-nginx
          ref: 9b683e40555fdfaba453d826306bc9c03880dc16 # 3.7.1
        includePaths:
          - charts/ingress-nginx/**/*
        excludePaths:
          - charts/ingress-nginx/ci/**/*
  - path: cluster/build/kubecf/_vendir
    contents:
      - path: manual
        manual: {}
      - path: upstream
        githubRelease:
          slug: cloudfoundry-incubator/kubecf
          tag: v2.5.8
          disableAutoChecksumValidation: true
          unpackArchive:
            path: kubecf-v2.5.8.tgz

  - path: cluster/config/cf-operator/_ytt_lib
    contents:
      - path: cf-operator
        manual: {}
  - path: cluster/config/ingress-nginx/_ytt_lib
    contents:
      - path: ingress-nginx
        manual: {}
  - path: cluster/config/kubecf/_ytt_lib
    contents:
      - path: kubecf
        manual: {}
