#@ load("@ytt:library", "library")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")

#@ def add_external_dns_namespace():
#@overlay/match by=overlay.all, expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  namespace: external-dns
#@ end

---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    istio-injection: disabled

--- #@ template.replace(overlay.apply(library.get("external-dns").eval(), add_external_dns_namespace()))
