---
controller:
  replicaCount: 1
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443

defaultBackend:
  enabled: false
