---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: concourse-web-web
    chart: concourse-11.4.1
    heritage: Helm
    release: concourse-web
  name: concourse-web-web
---
apiVersion: v1
data:
  host-key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBMkFVUFh4dWlEQy9xckJXaklkVDVmdk5jTWxNRVlwUjNYNFNMUUlnTEMxVUxEc0NPCmZsZUtaK1dpNFJ6d2JrVUtpS21KbTVHZXlOVlZDRGRmdmREMVNkMSs1ZmFxbXAyL09RQnpMUzdvOE5ZL2J0TXcKOGg5bHg0S1ZKYUpKMUVNMUVpeUdZNDFOeDU5MUtQMTRwQmZyMC9OZE9JckR1Mkp2RjZlN0NIRWJyemtONTdrYgpCVlFrYUlNYVMwMVJ3LzVPZTY4R0ZhbGxpMmlpOEw4ZE5XVlZ6cXVCaDVQd1ZXaW12VGd3djNUWUcyVEg4TDFWClY3bisvelJScGtqTWwyK1BVb3VHcUQrQnArNHdGK2hwNEFXNXYyNENxanRMSkVNdjRJRUp2MkZSZnJPYXVCSVoKWGpBUzFTU2c5VmFUT1MzaXd4YVlydjh1RzFYZk1GSElDdmtFUFFJREFRQUJBb0lCQUc4N1c4anJYNnZLMkptMwpvb0ovT2VGbXltaVhXc0N3RmkrMi9rVkNSLzJUMHRmTHl4Ty9XK05YMldEMUY5Q1ArSGFhWmVNWFBwM0hTN3VwClY4RlQ0Wm9oVllCd1hUUzBXWXl1Y0tBcGNZVGhyVlFScHpobGRuRWZDbEdRbVZlVks3U3AvS0V5VjRTYzFTVkEKTDJpL2NJMTQyTjJPaG03c3BxdVZrTGN1RnNWSU56WjBmWEN2MjVkVHFia0VnalRKek5kQnp5Rlh2YzR6ME10OQpnVzE0TTdteitZS1lPZnNDeElFbTQzOGZDOWIxNkM5NnlJRkJkTisvamFQOHBtYjJSb0lFMkQwRjhiajVLMWhSCll5R0ZLTU9VNGU2Y1lxNTlpV2Z1Ykt1dTJXTkpFQmsvNWFPN3g3WHUyUzBrOHdJWWx3eEZ1dTRMZlIyS3ZpenUKK21GVmYza0NnWUVBOWUwKzQwdEpHcE9QTThoQUIzRHdYalljOGxDdXlZZjN6MzBUM1JxVk5DVVZTV25sYWovcwozRU5pNitOZzN1K1pzOGNSMkNGb3UrakFDbFR5V0x1U25JOXlBQ0QwZXlXOW40YnpZTVViZ2RDNnZuZUxqcHp4CndXUjlYdjVSbVpWbHk3eFd1cWNnRWVFZjhSTmNZSTNvWGJ5MGxhRjNFT2J2dUF4LzRFVElrRmNDZ1lFQTRONDIKdzFVRVdHb3BXQklJWFlIa0VQSFF1RjBTeFIyQ1p5aDlFeFRlU3hGcGh5aWJrY0hSakRXK3Q5MVpMblNtNWsxTgpUT2RZdWMwQXBCVjNVK1RleGVGdkRJOTRML096ZTZIdDVNYXRSUXo4a1J3TUZHSkwzVHJwYmdUbVdkZkcwNUFkCm9pU2NKendZMTZvSlhuS3VzeGlrN1YrZ0NDTk5FMC8yVXVNblk0c0NnWUFFZjgycHZPUGVmNXFjR09ySytBNzkKdWtHM1VUQ1JjVkpnVW1wOW5oSGl2VmJ4VytXZGx3UFBWOUJFZm9sMEtyQUdNUHNybUJqaGJ6V3NPcmVnVmZZdAp0UlloMkhpQWxFVXUyUG8wNkFaRHpyekw1VVlCV3UrMVdSQk9INXNBazFJa2N4S25JWTJkcGgrK2Vsc3pUUVZXClNiQ0lHRWNrWVFVN3VjYlJKSkVDeXdLQmdCYjR2SEZ4OHZLeFRhM3drYWd6eDcrdlpGb2hML1N4RWd4Rng1azIKYllzUHFVOGtaOWdaQzdZZUczQ2ZEU2hBeEhnTWQ1UWVvaUxBL1lyRm9wNFFhRzJnblA2VWZYdXdrcXBUbllEYwpod0RoMWI5aE5SNno5L29PdGFBR29oMlZmSHRLWXF5WXZ0Y0hQYVp5ZVdpTG9Lc3RIbFFkaTdTcEhvdVZoSjF0CkZTNEhBb0dBR3krNTYrenZkUk9qSnk5QTJNbi80QnZXcnN1NFJTUUlMQko2SGI0VHBGNDZwMmZuMHJ3cXloT2oKT2Njcyt4a2RFc0k5dzVwaFh6SUVlT3EyTHF2V0hEUHh0ZExweE9ycm14NEFmdEFXZE04UzErT3FUcHpIaWhLMQp5MVpPcldmdk9OK1hqV0ZGQUVlai9DcFFaa05Va1R6alR0U0MwZG5mQXZlWmxhc1FIZEk9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
  local-users: dGVzdDp0ZXN0
  session-signing-key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBd0xxbC9yVUlhSStQWDdUbDNGV2NUZWU0c1FmOC9kYWFrQUxYeDk1NXRQd2tocWxZCmU0VDJWODRwL3lsRnZOV3BNNHZmY01ZS2ZNWTBKTEtnQWdCdkpoQ3l0U2tEQmhUQm9XbU42eUUwQUIxMVA5RW4KbElaUkJXTllxYUMyY1NnZTJaRDhxT1Nud2ZGaG5RQVc4KzdwRStFbEpBVmg3ZHRkRjNBNDc4SDUwbElpZ3E4SQp6TVdwMkVHSnBGQzcvVXUzNm9JTC8wM01OR0NtckgxanZ0VHVKaUFNUVVaWXlMMVJlQmt2dkhPenc5aTRIWFB5ClNNVnRjbGxtNE5CczJhVlB0d2hyMmt3U2tMdDh0MWJQZFJuNk9JeUVBdzVXa3R6QUthaVpua1R2ajZnM3h6ZHAKektjcmRsQnI5YXpubE52b1NpbkJVZnZ0d3lGbXZGTjFISGJBOXdJREFRQUJBb0lCQUU3Ry9EclVmSTlndnRYNwo5MGpNcFlzaWdGZThVQ2pobzJQaUJabG8wbzZyMGJKSlhpVisvOEo4UHFaUmxIUFBVYzRFQ2x6cVZqY1NQUllTCi9WeFVHUnFTRUxvRC9YeHExNHJHdm4reG5yTzlWc096Rmw2YldGcS9kT3BCQ3RITitHNHQyVmlmdmdLRVM4WUUKMTF6MTlzZHRhK1VCWGpuL1JGbmtRU0dmUkNJM1FxVGFZdmp4ZXZ0MHVXbHlQbXFrRlBRUXc4YnZISVh6b0IrQgpyemVpTWErK25NdmJYNXBBSDlYQTBCdmh5dUgzZkhpZFRVd2lWQnBrTWNwTFd0alAwQTBKVHNlY0RkYmluRERxCnVuMkVJbzh6TVdSd0tRTi9KblV4c2k4QVVFaWdCVENVcWVEZ1JFWHRXNjJ1dkZrU3BjVk1Yd21WaXR5TFlJVnkKcW5WTFVDRUNnWUVBNkl3WGtQMXFuU2ZjTmVvVkkveXBEdXoxL2tkcWNqU1BoTFllK2pkaUxMb0ZrTVc5QWxEbQpsendOYVdsVEZEOXlnbytOakpDbzYzL0E4SENtNTVzYWp3czVoWjZyMjB2ZFpjS0ZNazloMHFGNW9WQTdsa1EyCmd2RzJXYXpudVU3S2txaGZQK3BYaGlMZ1pLb0prc3QvK2c3cjZ1SHByZWR3RFk2aHhlQks0dnNDZ1lFQTFDcUgKOHl3QzVxVW8vMzZrUWcvVFUyYWROL1lFSGRKQUFiVTIzRVZyR1FTVm1uWFcwOEgyTkxGazB0c3hyd29ObmJncApQSWsySjdCaW1iSnZiTkQxN2licjRHQWtsRFRzUjhhSmtEbCswSmdOQ0FLOU4wN3FWdDFzN0ZYemhnOTVqVUw5CkVRVzU1ejYwR0FKcGVjcU53QTRKc2E4UDg1Mk4wMzU1T2JwOTJUVUNnWUJrT0J2ZjdKY0o2NmZIeEg0ZjZEK2oKb3hQUTVrNUZzY2s0VkpTOUdTbENSVmtvcjA5cHRCdnNpWUR1TU9vUkM5YjUxWXdYVEREQWJXcGxOT2Q1WVNydApBdFZqZEtKei9Cb0tSTzdLWTlPd3hzNTRhdStETHhxZkREU2VLUm9ram9SVytDRTBsblhwNVJYM3pDQWNGMytyCjhNcFRpOUQ5bFlTQkV6czg0QkRtQ1FLQmdRQ01jSDYvSzNIY0pKVm4wZmQrdHlVR2Z0VXc5c3N3eGp5U0pOYmsKcFpySDI2My9xV01EbHMrWGY1a2lyZTlNVTFaQ0FXWmlhTjBORm9lZC8yd2NWcEdFREFWMDU0OHUvMzByNGJLcgpZak9jZGhtaUpOWUZKMXFkRjBNRGliMkNEdnBCMUliWlhyWDQ2UnVqRE8ydXJiSjQzNUh4S05WaFIvaGFkOHhjCnR5S1l4UUtCZ0NWRGhOME1obmxVUUpWWmZYNDJBUG1GNGdRZzByM3NmTC9OR1hqRWpNSUtLRmU1YTg4ZVpWSHIKTDh4MStkcDBxN2N6QzhhL2wxRFV1aXdES2w4T0VweExzR0NxL0ovd0FmclNNUGlmdTZFVWxiVXdsSk9QZGdoYQorcC9LRkFlbEhYSjJ3Lzh5YWNrQWNhcmgzNVZQN2l4aHV2eHN3SE5kZ3Zmc0JURmNqbjMwCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
  worker-key-pub: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDNDk2RlNZRmNCQUtnRHRNc0JBSmlGLzYvTnhsWEtQNVVaZWN5RXNlZFl1VHQxR09nSlR3YUExcVoxTG1Ic2JmTERFNjhvRGRpTTR1dnhmSTR3dExoejU3dzN1MGpPVXhaMkplRjdTVndFZjFuVnFMbjRHaC9mOEdVTlFHU3lJcDF6VUQ1Qng5ZnEwUEF5UTQ3bXQ3VWZpODRyY2Y4TEtsN256QUlIVGNkZzJCdlRrUU45YlVHUGFxL1BiMVcyYktQQVF5NE96WFRTSXlyQUo4OVRIMmpGZWFaZnl4UUZHYkQ5alZISC95bDBvaU1yRGVhUllnY2NFNUlJK0tZN1dvTGpzQnJ5LzlRZjJFUkVMS1RLNFVlSUdJcVdjaTlsYWIxdGkrR3hGUFBpQzNrck5Gam80alNoVjRlVXM0Y05Jcmp3TnJ4VmFLUFhtVTZvN1kzSHBheXggQ29uY291cnNl
kind: Secret
metadata:
  labels:
    app: concourse-web-web
    chart: concourse-11.4.1
    heritage: Helm
    release: concourse-web
  name: concourse-web-web
type: Opaque
---
apiVersion: v1
data:
  pre-stop-hook.sh: |
    #!/bin/bash
    kill -s SIGUSR2 1
    while [ -e /proc/1 ]; do sleep 1; done
kind: ConfigMap
metadata:
  labels:
    app: concourse-web-worker
    chart: concourse-11.4.1
    heritage: Helm
    release: concourse-web
  name: concourse-web-worker
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: concourse-web-web
    chart: concourse-11.4.1
    heritage: Helm
    release: concourse-web
  name: concourse-web-web
spec:
  ports:
  - name: atc
    port: 8080
    targetPort: atc
  selector:
    app: concourse-web-web
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: concourse-web-web
    chart: concourse-11.4.1
    heritage: Helm
    release: concourse-web
  name: concourse-web-web-worker-gateway
spec:
  ports:
  - name: worker-gateway
    port: 2222
    targetPort: tsa
  selector:
    app: concourse-web-web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: 6.4.1
          Type: resolved
          URL: concourse/concourse:6.4.1
        URL: index.docker.io/concourse/concourse@sha256:516a0c6cd690223a16b61b9e8c1f43d06aaa4e97e4ae108f5cd71a7cd820f8ef
  labels:
    app: concourse-web-web
    chart: concourse-11.4.1
    heritage: Helm
    release: concourse-web
  name: concourse-web-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concourse-web-web
      release: concourse-web
  template:
    metadata:
      annotations:
        checksum/config: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        checksum/secrets: 8537d0c370c93f44b477c29fbc7d5cb15c4d830978c0e55c45a96110d55ce1fc
      labels:
        app: concourse-web-web
        release: concourse-web
    spec:
      containers:
      - args:
        - web
        env:
        - name: CONCOURSE_CLUSTER_NAME
          value: concourse-ci-gershman-io
        - name: CONCOURSE_ENABLE_GLOBAL_RESOURCES
          value: "true"
        - name: CONCOURSE_SECRET_RETRY_ATTEMPTS
          value: "5"
        - name: CONCOURSE_SECRET_RETRY_INTERVAL
          value: 1s
        - name: CONCOURSE_LOG_LEVEL
          value: info
        - name: CONCOURSE_BIND_PORT
          value: "8080"
        - name: CONCOURSE_BIND_IP
          value: 0.0.0.0
        - name: CONCOURSE_ADD_LOCAL_USER
          valueFrom:
            secretKeyRef:
              key: local-users
              name: concourse-web-web
        - name: CONCOURSE_EXTERNAL_URL
          value: http://concourse.ci.gershman.io
        - name: CONCOURSE_DEBUG_BIND_IP
          value: 127.0.0.1
        - name: CONCOURSE_DEBUG_BIND_PORT
          value: "8079"
        - name: CONCOURSE_INTERCEPT_IDLE_TIMEOUT
          value: 0m
        - name: CONCOURSE_GLOBAL_RESOURCE_CHECK_TIMEOUT
          value: 1h
        - name: CONCOURSE_RESOURCE_CHECKING_INTERVAL
          value: 1m
        - name: CONCOURSE_RESOURCE_WITH_WEBHOOK_CHECKING_INTERVAL
          value: 1m
        - name: CONCOURSE_CONTAINER_PLACEMENT_STRATEGY
          value: volume-locality
        - name: CONCOURSE_BAGGAGECLAIM_RESPONSE_HEADER_TIMEOUT
          value: 1m
        - name: CONCOURSE_BUILD_TRACKER_INTERVAL
          value: 10s
        - name: CONCOURSE_POSTGRES_HOST
          value: concourse-web-postgresql
        - name: CONCOURSE_POSTGRES_USER
          value: concourse
        - name: CONCOURSE_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: concourse-web-postgresql
        - name: CONCOURSE_POSTGRES_DATABASE
          value: concourse
        - name: CONCOURSE_GC_INTERVAL
          value: 30s
        - name: CONCOURSE_GC_ONE_OFF_GRACE_PERIOD
          value: 5m
        - name: CONCOURSE_GC_MISSING_GRACE_PERIOD
          value: 5m
        - name: CONCOURSE_AUTH_DURATION
          value: 24h
        - name: CONCOURSE_SESSION_SIGNING_KEY
          value: /concourse-keys/session_signing_key
        - name: CONCOURSE_MAIN_TEAM_LOCAL_USER
          value: test
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CONCOURSE_PEER_ADDRESS
          value: $(POD_IP)
        - name: CONCOURSE_TSA_LOG_LEVEL
          value: info
        - name: CONCOURSE_TSA_BIND_IP
          value: 0.0.0.0
        - name: CONCOURSE_TSA_BIND_PORT
          value: "2222"
        - name: CONCOURSE_TSA_DEBUG_BIND_IP
          value: 127.0.0.1
        - name: CONCOURSE_TSA_DEBUG_BIND_PORT
          value: "2221"
        - name: CONCOURSE_TSA_HOST_KEY
          value: /concourse-keys/host_key
        - name: CONCOURSE_TSA_AUTHORIZED_KEYS
          value: /concourse-keys/worker_key.pub
        - name: CONCOURSE_TSA_HEARTBEAT_INTERVAL
          value: 30s
        image: index.docker.io/concourse/concourse@sha256:516a0c6cd690223a16b61b9e8c1f43d06aaa4e97e4ae108f5cd71a7cd820f8ef
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/v1/info
            port: atc
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 3
        name: concourse-web-web
        ports:
        - containerPort: 8080
          name: atc
        - containerPort: 2222
          name: tsa
        - containerPort: 8079
          name: atc-debug
        readinessProbe:
          httpGet:
            path: /api/v1/info
            port: atc
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /concourse-keys
          name: concourse-keys
          readOnly: true
        - mountPath: /concourse-auth
          name: auth-keys
          readOnly: true
      serviceAccountName: concourse-web-web
      volumes:
      - name: concourse-keys
        secret:
          defaultMode: 256
          items:
          - key: host-key
            path: host_key
          - key: session-signing-key
            path: session_signing_key
          - key: worker-key-pub
            path: worker_key.pub
          secretName: concourse-web-web
      - name: auth-keys
        secret:
          defaultMode: 256
          items: null
          secretName: concourse-web-web
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-public
  labels:
    app: concourse-web-web
    chart: concourse-11.4.1
    heritage: Helm
    release: concourse-web
  name: concourse-web-web
spec:
  rules:
  - host: concourse.ci.gershman.io
    http:
      paths:
      - backend:
          serviceName: concourse-web-web
          servicePort: 8080
