# https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml
# http://alertmanager.vcap.me
# http://grafana.vcap.me
# http://prometheus.vcap.me
---
alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - alertmanager.vcap.me

grafana:
  adminPassword: prom-operator
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.vcap.me

kubelet:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

prometheusOperator:
  enabled: true
  logLevel: info

prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.vcap.me
  logLevel: info
  retention: 10m

  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs: []
