---
apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: spring-petclinic-tutorial
spec:
  tag: docker.pkg.github.com/aegershman/kpack-goof/spring-petclinic-tutorial
  serviceAccount: kpack-service-account
  builder:
    name: default
    kind: ClusterBuilder
  # cacheSize: "1.5Gi" # Optional, if not set then the caching feature is disabled
  failedBuildHistoryLimit: 5 # Optional, if not present defaults to 10
  successBuildHistoryLimit: 5 # Optional, if not present defaults to 10
  source:
    git:
      url: https://github.com/spring-projects/spring-petclinic
      revision: 82cb521d636b282340378d80a6307a08e3d4a4c4
