---
apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: spring-petclinic-tutorial
spec:
  # this is deceptive because you'd think it should be the ingress-addressable route,
  # but no! otherwise it'll resolve to the localhost of the build pod container itself
  # and not the "localhost" of the actual host machine which would route to the ingress
  # and thus to harbor-- no, instead, use the full cluster-internal DNS for tagging,
  # and make sure that 'harbor' has it's external_host configured as the cluster-internal DNS
  # so it returns the proper values to the client's docker auth endpoint resolver
  #
  # tag: harbor.vcap.me/library/spring-petclinic
  #
  # [analyze] ERROR: failed to get previous image: connect to repo store 'harbor-harbor-core.harbor.svc.cluster.local/library/spring-petclinic': GET http://harbor-harbor-core.harbor.svc.cluster.local/v2/library/spring-petclinic/manifests/latest: NOT_FOUND: repository library/spring-petclinic not found
  # tag: harbor-harbor-core.harbor.svc.cluster.local/library/spring-petclinic
  #
  # nope, this isn't it either:
  # [prepare] prepare:main.go:79: GET http://harbor-harbor-core.harbor.svc.cluster.local:80/service/token?scope=repository%3Alibrary%3Apush%2Cpull&service=harbor-registry: unsupported status code 500
  # tag: harbor-harbor-core.harbor.svc.cluster.local/library
  #
  # okay, not this either?
  # [prepare] prepare:main.go:83: invalid credentials to build to harbor-harbor-core.harbor.svc.cluster.local:80/library/spring-petclinic
  # tag: harbor-harbor-core.harbor.svc.cluster.local:80/library/spring-petclinic
  #
  tag: harbor-harbor-core.harbor.svc.cluster.local/library/spring-petclinic
  #
  serviceAccount: kpack-service-account
  builder:
    name: default
    kind: ClusterBuilder
  # cacheSize: "1.5Gi" # Optional, if not set then the caching feature is disabled
  failedBuildHistoryLimit: 5 # Optional, if not present defaults to 10
  successBuildHistoryLimit: 5 # Optional, if not present defaults to 10
  source:
    git:
      url: https://github.com/spring-projects/spring-petclinic
      revision: 82cb521d636b282340378d80a6307a08e3d4a4c4
