---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
  - path: cluster/build/yugabyte/_vendir
    contents:
      - path: manual
        manual: {}
      - path: upstream
        git:
          url: https://github.com/yugabyte/charts
          ref: 88cd63e8f9468d98db2aae9662570aeb11e377ac # 2.2.0
        includePaths:
          - stable/yugabyte/**/*

  - path: cluster/config/yugabyte/_ytt_lib
    contents:
      - path: yugabyte
        manual: {}
