---
apiVersion: gluon.starkandwayne.com/v1alpha1
kind: BOSHConfig
metadata:
  name: runtime-conf

spec:
  director: gluon-bosh-lite
  type: runtime
  config: |
    addons:
      - name: bosh-dns
        include:
          stemcell:
            - os: ubuntu-trusty
            - os: ubuntu-xenial
        jobs:
          - name: bosh-dns
            properties:
              api:
                client:
                  tls: ((/dns_api_client_tls))
                server:
                  tls: ((/dns_api_server_tls))
              cache:
                enabled: true
              health:
                client:
                  tls: ((/dns_healthcheck_client_tls))
                enabled: true
                server:
                  tls: ((/dns_healthcheck_server_tls))
            release: bosh-dns
    releases:
      - name: bosh-dns
        sha1: d61c2360c5a912379c0601a33b1e8b7c97ab30e0
        url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.21.0
        version: 1.21.0
    variables:
      - name: /dns_healthcheck_tls_ca
        options:
          common_name: dns-healthcheck-tls-ca
          is_ca: true
        type: certificate
      - name: /dns_healthcheck_server_tls
        options:
          ca: /dns_healthcheck_tls_ca
          common_name: health.bosh-dns
          extended_key_usage:
            - server_auth
        type: certificate
      - name: /dns_healthcheck_client_tls
        options:
          ca: /dns_healthcheck_tls_ca
          common_name: health.bosh-dns
          extended_key_usage:
            - client_auth
        type: certificate
      - name: /dns_api_tls_ca
        options:
          common_name: dns-api-tls-ca
          is_ca: true
        type: certificate
      - name: /dns_api_server_tls
        options:
          ca: /dns_api_tls_ca
          common_name: api.bosh-dns
          extended_key_usage:
            - server_auth
        type: certificate
      - name: /dns_api_client_tls
        options:
          ca: /dns_api_tls_ca
          common_name: api.bosh-dns
          extended_key_usage:
            - client_auth
        type: certificate
