---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: null
  labels:
    app: minibroker-minibroker
    chart: minibroker-0.0.0
    heritage: Helm
    release: minibroker
  name: minibroker
---
apiVersion: v1
data:
  provisioning-settings.yaml: |
    mariadb: {}
    mongodb: {}
    mysql: {}
    postgresql: {}
    rabbitmq: {}
    redis: {}
kind: ConfigMap
metadata:
  name: minibroker-provisioning-settings
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: minibroker-minibroker
    chart: minibroker-0.0.0
    heritage: Helm
    release: minibroker
  name: minibroker-minibroker
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - limitranges
  - persistentvolumeclaims
  - pods
  - podtemplates
  - replicationcontrollers
  - resourcequotas
  - secrets
  - serviceaccounts
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - apps
  - autoscaling
  - batch
  - networking.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: minibroker-minibroker
    chart: minibroker-0.0.0
    heritage: Helm
    release: minibroker
  name: minibroker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minibroker-minibroker
subjects:
- kind: ServiceAccount
  name: minibroker
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minibroker-minibroker
    chart: minibroker-0.0.0
    heritage: Helm
    release: minibroker
  name: minibroker-minibroker
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: broker
  selector:
    app: minibroker-minibroker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: canary
          Type: resolved
          URL: quay.io/kubernetes-service-catalog/minibroker:canary
        URL: quay.io/kubernetes-service-catalog/minibroker@sha256:1e5869edd429cd3b017b01ccd010cfd65ba80aefd0cec0d92e275a671b683fa6
  labels:
    app: minibroker-minibroker
    chart: minibroker-0.0.0
    heritage: Helm
    release: minibroker
  name: minibroker-minibroker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minibroker-minibroker
  strategy:
    type: null
  template:
    metadata:
      labels:
        app: minibroker-minibroker
        chart: minibroker-0.0.0
        heritage: Helm
        release: minibroker
    spec:
      containers:
      - args:
        - minibroker
        - --service-catalog-enabled-only
        - -defaultNamespace
        - minibroker
        - --port
        - "8080"
        - -v
        - "3"
        - -logtostderr
        - --provisioningSettings
        - /minibroker/provisioning-settings.yaml
        env:
        - name: CONFIG_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/kubernetes-service-catalog/minibroker@sha256:1e5869edd429cd3b017b01ccd010cfd65ba80aefd0cec0d92e275a671b683fa6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
        name: minibroker
        ports:
        - containerPort: 8080
          name: broker
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /minibroker
          name: provisioning-settings
          readOnly: true
      serviceAccountName: minibroker
      volumes:
      - configMap:
          name: minibroker-provisioning-settings
        name: provisioning-settings
