#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.and_op(overlay.subset({"metadata":{"name":"cf-system"}}), overlay.subset({"kind": "Namespace"}))
---
metadata:
  labels:
    #@overlay/match missing_ok=True
    cf-for-k8s.cloudfoundry.org/cf-system-ns: ""
