# http://alertmanager.vcap.me:32080
# https://alertmanager.vcap.me:32443
# http://grafana.vcap.me:32080
# https://grafana.vcap.me:32443
# http://prometheus.vcap.me:32080
# https://prometheus.vcap.me:32443
---
alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - alertmanager.vcap.me

grafana:
  adminPassword: prom-operator
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.vcap.me
  # https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml#L542
  additionalDataSources: []

prometheusOperator:
  enabled: true

prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.vcap.me

  # https://github.com/helm/charts/issues/11310
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
