helmDefaults:
  kubeContext: kind-kind

repositories: []

# https://cf-operators.s3.amazonaws.com/helm-charts/index.html
# https://github.com/cloudfoundry-incubator/cf-operator/releases
# https://scf-v3.s3.amazonaws.com/index.html
# https://github.com/SUSE/kubecf/blob/master/doc/dev/general.md
# https://github.com/SUSE/kubecf/blob/master/doc/dev/minikube.md
releases:
  - name: cf-operator
    namespace: kubecf
    chart: https://cf-operators.s3.amazonaws.com/helm-charts/cf-operator-v0.4.2-199.g57bec03f.tgz
    installed: true
    values:
      - config/cf-operator/values.yml

  - name: kubecf
    namespace: kubecf
    chart: https://scf-v3.s3.amazonaws.com/kubecf-3.0.0-4a01e41.tgz
    installed: true
    values:
      - config/kubecf/values.yml

  - name: nginx
    namespace: kubecfl
    chart: stable/nginx-ingress
    installed: true
    version: ~1.x.x
    values:
      - config/nginx/values.yml
