---
helmDefaults:
  kubeContext: kind-kind
  createNamespace: true
  wait: false

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: minibroker
    url: https://minibroker.blob.core.windows.net/charts
  - name: quarks
    url: https://cloudfoundry-incubator.github.io/quarks-helm
  - name: stratos
    url: https://cloudfoundry.github.io/stratos

releases:
  - name: cf-operator
    namespace: cf-operator
    chart: quarks/cf-operator
    version: 4.5.6
    installed: true
    values:
      - config/cf-operator/values.yml

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    installed: true
    version: ~2.7.x
    values:
      - config/ingress-nginx/values.yml

  - name: kubecf
    namespace: kubecf
    createNamespace: false
    chart: https://github.com/cloudfoundry-incubator/kubecf/releases/download/v2.2.2/kubecf-v2.2.2.tgz
    installed: true
    needs:
      - cf-operator/cf-operator
      - ingress-nginx/ingress-nginx
    values:
      - config/kubecf/values.yml

  - name: minibroker
    namespace: minibroker
    chart: minibroker/minibroker
    installed: true
    version: ~0.x.x
    values:
      - config/minibroker/values.yml

  - name: stratos
    namespace: stratos
    chart: stratos/console
    installed: false
    version: ~3.2.x
    needs:
      - kubecf/kubecf
      - ingress-nginx/ingress-nginx
    values:
      - config/stratos/values.yml
