---
version: "2"

# https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/deploy-local.md#steps-to-deploy-on-kind
# https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/deploy.md
tasks:
  has-binaries:
    cmds:
      - which bosh
      - which cf
      - which kapp
      - which ytt

  vendir:
    cmds:
      - vendir sync

  apply-metrics-server:
    cmds:
      - kubectl apply --recursive --filename config/vendor/github.com/kubernetes-sigs

  generate-values:
    cmds:
      - | # I'm assuming vcap.me == nip.io == xip.io, allowing for localhost dns
        ./config/vendor/github.com/cloudfoundry/cf-for-k8s/hack/generate-values.sh \
          --cf-domain vcap.me \
          >config/values/cf-values.yml

  apply-cf:
    cmds:
      - |
        ytt \
          -f config/vendor/github.com/cloudfoundry/cf-for-k8s/config \
          -f config/values/cf-values.yml \
          -f config/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/remove-resource-requirements.yml \
          -f config/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/remove-ingressgateway-service.yml \
          >config/values/cf-for-k8s-ytt.yml
      - kapp deploy -a cf -f config/values/cf-for-k8s-ytt.yml

  post-install:
    cmds:
      - |
        cf api --skip-ssl-validation https://api.vcap.me
