---
version: "2"

# https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/deploy-local.md#steps-to-deploy-on-kind
# https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/deploy.md
tasks:
  has-binaries:
    cmds:
      - which bosh
      - which cf
      - which kapp
      - which ytt

  vendir:
    cmds:
      - vendir sync

  generate-values:
    cmds:
      - |
        ./config/vendor/github.com/cloudfoundry/cf-for-k8s/hack/generate-values.sh \
          --cf-domain vcap.me > /tmp/cf-values.yml

  apply-metrics-server:
    cmds:
      - kubectl apply --recursive --filename config/vendor/github.com/kubernetes-sigs
