---
version: "2"

# https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/deploy-local.md#steps-to-deploy-on-kind
# https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/deploy.md
tasks:
  has-binaries:
    cmds:
      - which bosh
      - which cf
      - which kapp
      - which ytt

  apply-metrics-server:
    cmds:
      - kubectl apply --recursive --filename vendor/github.com/kubernetes-sigs
