---
version: "2"

# https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/deploy-local.md#steps-to-deploy-on-kind
# https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/deploy.md
tasks:
  kind-create:
    cmds:
      - |
        kind create cluster \
          --config config/vendor/github.com/cloudfoundry/cf-for-k8s/deploy/kind/cluster.yml \
          --image='kindest/node:v1.18.2'

  apply-metrics-server:
    cmds:
      - kubectl apply --recursive --filename config/vendor/github.com/kubernetes-sigs

  generate-values:
    cmds:
      - | # I'm assuming vcap.me == nip.io == xip.io, allowing for localhost dns
        ./config/vendor/github.com/cloudfoundry/cf-for-k8s/hack/generate-values.sh \
          --cf-domain vcap.me \
          >config/values/cf-values.yml
      - |
        ytt \
          -f config/vendor/github.com/cloudfoundry/cf-for-k8s/config \
          -f config/values/cf-values.yml \
          -f config/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/remove-resource-requirements.yml \
          -f config/vendor/github.com/cloudfoundry/cf-for-k8s/config-optional/remove-ingressgateway-service.yml \
          >config/values/cf-for-k8s-ytt.yml

  clean-generated-values:
    cmds:
      - | # when you remove these from /tmp and re-run the generate-values script it'll give you new passwords, certs, etc.
        rm -f /tmp/cf-values.yml
        rm -f /tmp/cf-for-k8s-ytt.yml
        rm -rf /tmp/vcap.me

  apply-cf:
    cmds:
      - kapp deploy -a cf -f config/values/cf-for-k8s-ytt.yml --yes

  delete-cf:
    cmds:
      - kapp delete -a cf -y

  post-install:
    cmds:
      - |
        cf api --skip-ssl-validation https://api.vcap.me
        cf auth admin $(yq r config/values/cf-values.yml 'cf_admin_password')
      - |
        cf create-org test-org
        cf create-space -o test-org test-space
        cf target -o test-org -s test-space
      - |
        cf enable-feature-flag diego_docker
        cf push -f config/values/example-docker-cf-manifest.yml
      - |
        cf push test-node-app -p config/vendor/github.com/cloudfoundry/cf-for-k8s/tests/smoke/assets/test-node-app
        curl http://test-node-app.vcap.me/env

  full-install-steps:
    cmds:
      # - task: kind-create
      - task: apply-metrics-server
      # - task: clean-generated-values
      - task: generate-values
      - task: apply-cf
      # - task: post-install

  debug:
    cmds:
      - | # not intended to be ran as a task, just for holding command strings
        exit 1
        kubectl -n cf-system logs -f -lapp=log-cache --all-containers --max-log-requests=6
