# https://github.com/k14s/vendir/blob/master/examples/git-and-manual/vendir.yml
---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: config/vendor
    contents:
      - path: github.com/kubernetes-sigs/metrics-server
        githubRelease:
          slug: kubernetes-sigs/metrics-server
          tag: v0.3.6
          disableAutoChecksumValidation: true
        includePaths:
          - components.yaml
  - path: config/values
    manual: {}
