# https://github.com/actions/labeler
---
name: "apply-labels-on-prs"

on: [pull_request]

jobs:
  apply-labels-on-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
