# https://github.com/actions/labeler
# https://github.com/crazy-max/ghaction-github-labeler
---
name: "apply-labels"

on: [push, pull_request]

jobs:
  configure-repository-labels:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run-labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v2
        with:
          yaml_file: .github/labels.yml
          skip_delete: false
          dry_run: false
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  apply-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
