# https://github.com/crazy-max/ghaction-github-labeler
---
name: "configure-repo-labels"

on:
  push:
    paths:
      - .github/**/*
  workflow_dispatch: {}

jobs:
  configure-repo-labels:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run-labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v4.2.0
        with:
          dry-run: false
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          skip-delete: false
          yaml-file: .github/labels.yml
