---
controller:
  replicaCount: 1
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    type: NodePort
  config:
    proxy-body-size: 64m
    proxy-buffer-size: 16k
  metrics:
    enabled: false
    service:
      type: ClusterIP
    serviceMonitor:
      enabled: false
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

defaultBackend:
  enabled: false
